"""Declarative registry for curated manufacturing drawings.

The registry is intentionally data-only.  Each drawing has its own statically
importable recipe so changing one print cannot invalidate every other print.
Both ``dodo.py`` and ``cut_release.py`` consume this module, keeping build and
release artifact lists in lockstep as the book's drawing set grows.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parent
CAD_ROOT = SCRIPTS_DIR.parent
TEMPLATES_DIR = CAD_ROOT / "templates"
# Each drawing's layout-audit report (``_drawing_layout_audit``): a declared
# drawing-task target, so it rides the remote cache with the sheet it audits.
LAYOUT_REPORT_DIR = CAD_ROOT / "out" / "reports" / "layout-audit"


def layout_report_path(artifact_stem: str) -> Path:
    return LAYOUT_REPORT_DIR / f"{artifact_stem}.json"


class DrawingLayout(StrEnum):
    LANDSCAPE = "landscape"
    PORTRAIT = "portrait"


@dataclass(frozen=True)
class DrawingTemplateSpec:
    path: Path
    width_m: float
    height_m: float
    dpi: int
    pixel_size: tuple[int, int]
    title_block_left_m: float
    title_block_top_m: float


# Hand-made in SolidWorks (title block, tolerance block, embedded ASME B sheet
# format) -- NOT generated; see cad/templates/README.md. Both orientations embed
# their own sheet formats, so there are no separate .slddrt runtime dependencies.
DRAWING_TEMPLATES = {
    DrawingLayout.LANDSCAPE: DrawingTemplateSpec(
        path=TEMPLATES_DIR / "harmonic-analyzer-landscape.DRWDOT",
        width_m=0.4318,
        height_m=0.2794,
        dpi=300,
        pixel_size=(5100, 3300),
        title_block_left_m=0.216,
        title_block_top_m=0.066,
    ),
    DrawingLayout.PORTRAIT: DrawingTemplateSpec(
        path=TEMPLATES_DIR / "harmonic-analyzer-portrait.DRWDOT",
        width_m=0.2794,
        height_m=0.4318,
        dpi=300,
        pixel_size=(3300, 5100),
        title_block_left_m=0.0636,
        title_block_top_m=0.066,
    ),
}


@dataclass(frozen=True)
class DrawingSpec:
    name: str
    part: str
    artifact_stem: str
    script_name: str
    layout: DrawingLayout
    # "part" (default) draws a cad/out/sldprt SLDPRT; "assembly" draws the
    # cad/out/sldasm SLDASM of the assembly build named by ``part``.
    source_kind: str = "part"
    additional_layouts: tuple[DrawingLayout, ...] = ()

    @property
    def script(self) -> Path:
        return SCRIPTS_DIR / self.script_name

    @property
    def source(self) -> Path:
        """The authoritative CAD model this drawing documents.

        Build scripts emit dashed artefact names (``ch_fulcrum_shaft`` ->
        ``ch-fulcrum-shaft.SLDPRT``, ``pn_pen`` -> ``pn-pen.SLDASM``), so the source stem
        is the dashed ``part``.
        """
        stem = self.part.replace("_", "-")
        if self.source_kind == "assembly":
            return CAD_ROOT / "out" / "sldasm" / f"{stem}.SLDASM"
        return CAD_ROOT / "out" / "sldprt" / f"{stem}.SLDPRT"

    @property
    def outputs(self) -> dict[str, Path]:
        return {
            "slddrw": CAD_ROOT / "out" / "slddrw" / f"{self.artifact_stem}.SLDDRW",
            "pdf": CAD_ROOT / "out" / "pdf" / f"{self.artifact_stem}.pdf",
            "png": CAD_ROOT / "out" / "png" / f"{self.artifact_stem}_drawing.png",
        }

    @property
    def layout_report(self) -> Path:
        """The layout-audit report: a task target, but not a release output."""
        return layout_report_path(self.artifact_stem)

    @property
    def assets(self) -> tuple[Path, ...]:
        layouts = dict.fromkeys((self.layout, *self.additional_layouts))
        return tuple(DRAWING_TEMPLATES[layout].path for layout in layouts)


DRAWINGS: tuple[DrawingSpec, ...] = (
    DrawingSpec(
        name="pd_platen_guide",
        part="pd_platen_guide",
        artifact_stem="pd-platen-guide",
        script_name="draw_pd_platen_guide.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_arm",
        part="dt_crank_arm",
        artifact_stem="dt-crank-arm",
        script_name="draw_dt_crank_arm.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_hub",
        part="dt_crank_hub",
        artifact_stem="dt-crank-hub",
        script_name="draw_dt_crank_hub.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_crank_hub_pin",
        part="vn_crank_hub_pin",
        artifact_stem="vn-crank-hub-pin",
        script_name="draw_vn_crank_hub_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_handle_pivot_screw",
        part="dt_crank_handle_pivot_screw",
        artifact_stem="dt-crank-handle-pivot-screw",
        script_name="draw_dt_crank_handle_pivot_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="fr_rocker_arm_support",
        part="fr_rocker_arm_support",
        artifact_stem="fr-rocker-arm-support",
        script_name="draw_fr_rocker_arm_support.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_tip_collar",
        part="vn_cone_tip_collar",
        artifact_stem="vn-cone-tip-collar",
        script_name="draw_vn_cone_tip_collar.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_fulcrum_shaft",
        part="ch_fulcrum_shaft",
        artifact_stem="ch-fulcrum-shaft",
        script_name="draw_ch_fulcrum_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_fulcrum_keeper",
        part="ch_fulcrum_keeper",
        artifact_stem="ch-fulcrum-keeper",
        script_name="draw_ch_fulcrum_keeper.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_pivot_shaft",
        part="ch_pivot_shaft",
        artifact_stem="ch-pivot-shaft",
        script_name="draw_ch_pivot_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_assembly",
        part="pn_pen",
        artifact_stem="pn-pen-assembly",
        script_name="draw_pn_pen_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_lift_rod",
        part="dt_pinion_lift_rod",
        artifact_stem="dt-pinion-lift-rod",
        script_name="draw_dt_pinion_lift_rod.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cylinder_gear_shaft",
        part="dt_cylinder_gear_shaft",
        artifact_stem="dt-cylinder-gear-shaft",
        script_name="draw_dt_cylinder_gear_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_arbor",
        part="dt_pinion_arbor",
        artifact_stem="dt-pinion-arbor",
        script_name="draw_dt_pinion_arbor.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_marker",
        part="pn_pen_marker",
        artifact_stem="pn-pen-marker",
        script_name="draw_pn_pen_marker.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_pin",
        part="pd_transgear_pin",
        artifact_stem="pd-transgear-pin",
        script_name="draw_pd_transgear_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_guide_lock",
        part="pd_guide_lock",
        artifact_stem="pd-guide-lock",
        script_name="draw_pd_guide_lock.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_wheel_axle",
        part="mg_wheel_axle",
        artifact_stem="mg-wheel-axle",
        script_name="draw_mg_wheel_axle.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="sh_column_clamp_front",
        part="sh_column_clamp_front",
        artifact_stem="sh-column-clamp-front",
        script_name="draw_sh_column_clamp_front.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_pivot_block",
        part="dt_pinion_pivot_block",
        artifact_stem="dt-pinion-pivot-block",
        script_name="draw_dt_pinion_pivot_block.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_v_block",
        part="pn_pen_v_block",
        artifact_stem="pn-pen-v-block",
        script_name="draw_pn_pen_v_block.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_pin",
        part="dt_crank_pin",
        artifact_stem="dt-crank-pin",
        script_name="draw_dt_crank_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_rod",
        part="pn_pen_rod",
        artifact_stem="pn-pen-rod",
        script_name="draw_pn_pen_rod.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_magnifying_lever",
        part="mg_magnifying_lever",
        artifact_stem="mg-magnifying-lever",
        script_name="draw_mg_magnifying_lever.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_magnifying_vertical_rod",
        part="mg_magnifying_vertical_rod",
        artifact_stem="mg-magnifying-vertical-rod",
        script_name="draw_mg_magnifying_vertical_rod.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_magnifying_clamp",
        part="mg_magnifying_clamp",
        artifact_stem="mg-magnifying-clamp",
        script_name="draw_mg_magnifying_clamp.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="sm_knife_mount",
        part="sm_knife_mount",
        artifact_stem="sm-knife-mount",
        script_name="draw_sm_knife_mount.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_wheel_bar",
        part="mg_wheel_bar",
        artifact_stem="mg-wheel-bar",
        script_name="draw_mg_wheel_bar.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_magnifying_wheel",
        part="mg_magnifying_wheel",
        artifact_stem="mg-magnifying-wheel",
        script_name="draw_mg_magnifying_wheel.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_magnifying_bracket",
        part="mg_magnifying_bracket",
        artifact_stem="mg-magnifying-bracket",
        script_name="draw_mg_magnifying_bracket.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_lever_wire",
        part="mg_lever_wire",
        artifact_stem="mg-lever-wire",
        script_name="draw_mg_lever_wire.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_rocker_arm",
        part="ch_rocker_arm",
        artifact_stem="ch-rocker-arm",
        script_name="draw_ch_rocker_arm.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_connecting_rod",
        part="ch_connecting_rod",
        artifact_stem="ch-connecting-rod",
        script_name="draw_ch_connecting_rod.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_channel_lever",
        part="ch_channel_lever",
        artifact_stem="ch-channel-lever",
        script_name="draw_ch_channel_lever.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_amplitude_bar",
        part="ch_amplitude_bar",
        artifact_stem="ch-amplitude-bar",
        script_name="draw_ch_amplitude_bar.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_counter_spring",
        part="vn_counter_spring",
        artifact_stem="vn-counter-spring",
        script_name="draw_vn_counter_spring.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_keeper_chain",
        part="vn_keeper_chain",
        artifact_stem="vn-keeper-chain",
        script_name="draw_vn_keeper_chain.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_keeper_chain_link",
        part="vn_keeper_chain_link",
        artifact_stem="vn-keeper-chain-link",
        script_name="draw_vn_keeper_chain_link.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_channel_spring_installed",
        part="vn_channel_spring_installed",
        artifact_stem="vn-channel-spring-installed",
        script_name="draw_vn_channel_spring_installed.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_spring_hook",
        part="vn_spring_hook",
        artifact_stem="vn-spring-hook",
        script_name="draw_vn_spring_hook.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="sm_summing_lever",
        part="sm_summing_lever",
        artifact_stem="sm-summing-lever",
        script_name="draw_sm_summing_lever.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_arbor_collar",
        part="dt_pinion_arbor_collar",
        artifact_stem="dt-pinion-arbor-collar",
        script_name="draw_dt_pinion_arbor_collar.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_bracket",
        part="dt_pinion_bracket",
        artifact_stem="dt-pinion-bracket",
        script_name="draw_dt_pinion_bracket.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_lever",
        part="dt_pinion_lever",
        artifact_stem="dt-pinion-lever",
        script_name="draw_dt_pinion_lever.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_cam",
        part="dt_pinion_cam",
        artifact_stem="dt-pinion-cam",
        script_name="draw_dt_pinion_cam.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_cam_pin",
        part="dt_pinion_cam_pin",
        artifact_stem="dt-pinion-cam-pin",
        script_name="draw_dt_pinion_cam_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_lever_pin",
        part="dt_pinion_lever_pin",
        artifact_stem="dt-pinion-lever-pin",
        script_name="draw_dt_pinion_lever_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_pivot_shaft",
        part="dt_pinion_pivot_shaft",
        artifact_stem="dt-pinion-pivot-shaft",
        script_name="draw_dt_pinion_pivot_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_handle",
        part="dt_pinion_handle",
        artifact_stem="dt-pinion-handle",
        script_name="draw_dt_pinion_handle.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_pinion_spring",
        part="dt_pinion_spring",
        artifact_stem="dt-pinion-spring",
        script_name="draw_dt_pinion_spring.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_handle",
        part="dt_crank_handle",
        artifact_stem="dt-crank-handle",
        script_name="draw_dt_crank_handle.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_handle_ferrule",
        part="dt_crank_handle_ferrule",
        artifact_stem="dt-crank-handle-ferrule",
        script_name="draw_dt_crank_handle_ferrule.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_handle_butt_cup",
        part="dt_crank_handle_butt_cup",
        artifact_stem="dt-crank-handle-butt-cup",
        script_name="draw_dt_crank_handle_butt_cup.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_boss_hook",
        part="vn_boss_hook",
        artifact_stem="vn-boss-hook",
        script_name="draw_vn_boss_hook.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="mg_output_fixture",
        part="mg_output_fixture",
        artifact_stem="mg-output-fixture",
        script_name="draw_mg_output_fixture.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_frame",
        part="pn_pen_frame",
        artifact_stem="pn-pen-frame",
        script_name="draw_pn_pen_frame.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_hanger",
        part="pn_pen_hanger",
        artifact_stem="pn-pen-hanger",
        script_name="draw_pn_pen_hanger.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pn_pen_wire",
        part="pn_pen_wire",
        artifact_stem="pn-pen-wire",
        script_name="draw_pn_pen_wire.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="sm_gooseneck",
        part="sm_gooseneck",
        artifact_stem="sm-gooseneck",
        script_name="draw_sm_gooseneck.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ha_measuring_stick",
        part="ha_measuring_stick",
        artifact_stem="ha-measuring-stick",
        script_name="draw_ha_measuring_stick.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cylinder_gear",
        part="dt_cylinder_gear",
        artifact_stem="dt-cylinder-gear",
        script_name="draw_dt_cylinder_gear.py",
        layout=DrawingLayout.PORTRAIT,
    ),
    DrawingSpec(
        name="dt_cone_gear",
        part="dt_cone_gear",
        artifact_stem="dt-cone-gear",
        script_name="draw_dt_cone_gear.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_drive_gear",
        part="dt_crank_drive_gear",
        artifact_stem="dt-crank-drive-gear",
        script_name="draw_dt_crank_drive_gear.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_pinion",
        part="dt_crank_pinion",
        artifact_stem="dt-crank-pinion",
        script_name="draw_dt_crank_pinion.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_pinion_pin",
        part="dt_crank_pinion_pin",
        artifact_stem="dt-crank-pinion-pin",
        script_name="draw_dt_crank_pinion_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_alignment_pinion",
        part="dt_alignment_pinion",
        artifact_stem="dt-alignment-pinion",
        script_name="draw_dt_alignment_pinion.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_rack_pinion",
        part="pd_rack_pinion",
        artifact_stem="pd-rack-pinion",
        script_name="draw_pd_rack_pinion.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_feed_pinion",
        part="pd_transgear_feed_pinion",
        artifact_stem="pd-transgear-feed-pinion",
        script_name="draw_pd_transgear_feed_pinion.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_removable",
        part="pd_transgear_removable",
        artifact_stem="pd-transgear-removable",
        script_name="draw_pd_transgear_removable.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cone_gear_shaft",
        part="dt_cone_gear_shaft",
        artifact_stem="dt-cone-gear-shaft",
        script_name="draw_dt_cone_gear_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cone_pivot_post",
        part="dt_cone_pivot_post",
        artifact_stem="dt-cone-pivot-post",
        script_name="draw_dt_cone_pivot_post.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cone_tip_block",
        part="dt_cone_tip_block",
        artifact_stem="dt-cone-tip-block",
        script_name="draw_dt_cone_tip_block.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cylinder_end_disc",
        part="dt_cylinder_end_disc",
        artifact_stem="dt-cylinder-end-disc",
        script_name="draw_dt_cylinder_end_disc.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_rocker_thrust_washer",
        part="ch_rocker_thrust_washer",
        artifact_stem="ch-rocker-thrust-washer",
        script_name="draw_ch_rocker_thrust_washer.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_cone_pivot_post_tl_cap_jaw_button",
        part="dt_cone_pivot_post_tl_cap_jaw_button",
        artifact_stem="dt-cone-pivot-post-tl-cap-jaw-button",
        script_name="draw_dt_cone_pivot_post_tl_cap_jaw_button.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_rocker_arm_tl_vise_stop",
        part="ch_rocker_arm_tl_vise_stop",
        artifact_stem="ch-rocker-arm-tl-vise-stop",
        script_name="draw_ch_rocker_arm_tl_vise_stop.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_arbor_pedestal",
        part="dt_arbor_pedestal",
        artifact_stem="dt-arbor-pedestal",
        script_name="draw_dt_arbor_pedestal.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crankshaft",
        part="dt_crankshaft",
        artifact_stem="dt-crankshaft",
        script_name="draw_dt_crankshaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_crank_seat_washer",
        part="dt_crank_seat_washer",
        artifact_stem="dt-crank-seat-washer",
        script_name="draw_dt_crank_seat_washer.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="fr_harmonic_base",
        part="fr_harmonic_base",
        artifact_stem="fr-harmonic-base",
        script_name="draw_fr_harmonic_base.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="fr_top_frame",
        part="fr_top_frame",
        artifact_stem="fr-top-frame",
        script_name="draw_fr_top_frame.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="fr_tube_frame",
        part="fr_tube_frame",
        artifact_stem="fr-tube-frame",
        script_name="draw_fr_tube_frame.py",
        layout=DrawingLayout.PORTRAIT,
    ),
    DrawingSpec(
        name="dt_cone_swing_platform",
        part="dt_cone_swing_platform",
        artifact_stem="dt-cone-swing-platform",
        script_name="draw_dt_cone_swing_platform.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_clamp_screw",
        part="vn_clamp_screw",
        artifact_stem="vn-clamp-screw",
        script_name="draw_vn_clamp_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_lock_knob",
        part="vn_cone_lock_knob",
        artifact_stem="vn-cone-lock-knob",
        script_name="draw_vn_cone_lock_knob.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_pivot_screw",
        part="vn_cone_pivot_screw",
        artifact_stem="vn-cone-pivot-screw",
        script_name="draw_vn_cone_pivot_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_tip_adjuster",
        part="vn_cone_tip_adjuster",
        artifact_stem="vn-cone-tip-adjuster",
        script_name="draw_vn_cone_tip_adjuster.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_tip_pinch_screw",
        part="vn_cone_tip_pinch_screw",
        artifact_stem="vn-cone-tip-pinch-screw",
        script_name="draw_vn_cone_tip_pinch_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_cone_tip_block_screw",
        part="vn_cone_tip_block_screw",
        artifact_stem="vn-cone-tip-block-screw",
        script_name="draw_vn_cone_tip_block_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_fillister_screw",
        part="vn_fillister_screw",
        artifact_stem="vn-fillister-screw",
        script_name="draw_vn_fillister_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_foot_screw",
        part="vn_foot_screw",
        artifact_stem="vn-foot-screw",
        script_name="draw_vn_foot_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_guide_lock_screw",
        part="vn_guide_lock_screw",
        artifact_stem="vn-guide-lock-screw",
        script_name="draw_vn_guide_lock_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_latch_hook_bracket_screw",
        part="vn_latch_hook_bracket_screw",
        artifact_stem="vn-latch-hook-bracket-screw",
        script_name="draw_vn_latch_hook_bracket_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_latch_hook_bracket",
        part="pd_latch_hook_bracket",
        artifact_stem="pd-latch-hook-bracket",
        script_name="draw_pd_latch_hook_bracket.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_latch_hook",
        part="pd_latch_hook",
        artifact_stem="pd-latch-hook",
        script_name="draw_pd_latch_hook.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_latch_hook_rivet",
        part="vn_latch_hook_rivet",
        artifact_stem="vn-latch-hook-rivet",
        script_name="draw_vn_latch_hook_rivet.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_pedestal_hold_down_screw",
        part="vn_pedestal_hold_down_screw",
        artifact_stem="vn-pedestal-hold-down-screw",
        script_name="draw_vn_pedestal_hold_down_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_pinion_strap_pin",
        part="vn_pinion_strap_pin",
        artifact_stem="vn-pinion-strap-pin",
        script_name="draw_vn_pinion_strap_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_crank_seat_drive_pin",
        part="vn_crank_seat_drive_pin",
        artifact_stem="vn-crank-seat-drive-pin",
        script_name="draw_vn_crank_seat_drive_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_knob_shaft",
        part="pd_transgear_knob_shaft",
        artifact_stem="pd-transgear-knob-shaft",
        script_name="draw_pd_transgear_knob_shaft.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_knob_drive_pin",
        part="vn_transgear_knob_drive_pin",
        artifact_stem="vn-transgear-knob-drive-pin",
        script_name="draw_vn_transgear_knob_drive_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_thumbnut",
        part="pd_transgear_thumbnut",
        artifact_stem="pd-transgear-thumbnut",
        script_name="draw_pd_transgear_thumbnut.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_knob_thrust_ring",
        part="pd_transgear_knob_thrust_ring",
        artifact_stem="pd-transgear-knob-thrust-ring",
        script_name="draw_pd_transgear_knob_thrust_ring.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_disc_hub",
        part="pd_transgear_disc_hub",
        artifact_stem="pd-transgear-disc-hub",
        script_name="draw_pd_transgear_disc_hub.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_knob_cup",
        part="pd_transgear_knob_cup",
        artifact_stem="pd-transgear-knob-cup",
        script_name="draw_pd_transgear_knob_cup.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_disc_screw",
        part="vn_transgear_disc_screw",
        artifact_stem="vn-transgear-disc-screw",
        script_name="draw_vn_transgear_disc_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_arm_plate_screw",
        part="vn_transgear_arm_plate_screw",
        artifact_stem="vn-transgear-arm-plate-screw",
        script_name="draw_vn_transgear_arm_plate_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_pivot_screw",
        part="vn_transgear_pivot_screw",
        artifact_stem="vn-transgear-pivot-screw",
        script_name="draw_vn_transgear_pivot_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_pivot_spacer",
        part="pd_transgear_pivot_spacer",
        artifact_stem="pd-transgear-pivot-spacer",
        script_name="draw_pd_transgear_pivot_spacer.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_rear_bushing",
        part="pd_transgear_rear_bushing",
        artifact_stem="pd-transgear-rear-bushing",
        script_name="draw_pd_transgear_rear_bushing.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_front_bushing",
        part="pd_transgear_front_bushing",
        artifact_stem="pd-transgear-front-bushing",
        script_name="draw_pd_transgear_front_bushing.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_drive_collar",
        part="pd_transgear_drive_collar",
        artifact_stem="pd-transgear-drive-collar",
        script_name="draw_pd_transgear_drive_collar.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_collar_cross_pin",
        part="vn_transgear_collar_cross_pin",
        artifact_stem="vn-transgear-collar-cross-pin",
        script_name="draw_vn_transgear_collar_cross_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_knob_cup_pin",
        part="vn_transgear_knob_cup_pin",
        artifact_stem="vn-transgear-knob-cup-pin",
        script_name="draw_vn_transgear_knob_cup_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_latch_pin",
        part="vn_transgear_latch_pin",
        artifact_stem="vn-transgear-latch-pin",
        script_name="draw_vn_transgear_latch_pin.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_retaining_ring",
        part="vn_transgear_retaining_ring",
        artifact_stem="vn-transgear-retaining-ring",
        script_name="draw_vn_transgear_retaining_ring.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_transgear_pivot_spring",
        part="vn_transgear_pivot_spring",
        artifact_stem="vn-transgear-pivot-spring",
        script_name="draw_vn_transgear_pivot_spring.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_arm",
        part="pd_transgear_arm",
        artifact_stem="pd-transgear-arm",
        script_name="draw_pd_transgear_arm.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_transgear_arm_plate",
        part="pd_transgear_arm_plate",
        artifact_stem="pd-transgear-arm-plate",
        script_name="draw_pd_transgear_arm_plate.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_frame_side_screw",
        part="vn_frame_side_screw",
        artifact_stem="vn-frame-side-screw",
        script_name="draw_vn_frame_side_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_frame_cross_screw",
        part="vn_frame_cross_screw",
        artifact_stem="vn-frame-cross-screw",
        script_name="draw_vn_frame_cross_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_tube_frame_cap",
        part="vn_tube_frame_cap",
        artifact_stem="vn-tube-frame-cap",
        script_name="draw_vn_tube_frame_cap.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_gooseneck_set_screw",
        part="vn_gooseneck_set_screw",
        artifact_stem="vn-gooseneck-set-screw",
        script_name="draw_vn_gooseneck_set_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_hanger_screw",
        part="vn_hanger_screw",
        artifact_stem="vn-hanger-screw",
        script_name="draw_vn_hanger_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_hex_bolt",
        part="vn_hex_bolt",
        artifact_stem="vn-hex-bolt",
        script_name="draw_vn_hex_bolt.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_knife_hanger_stud",
        part="vn_knife_hanger_stud",
        artifact_stem="vn-knife-hanger-stud",
        script_name="draw_vn_knife_hanger_stud.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_knife_hanger_washer",
        part="vn_knife_hanger_washer",
        artifact_stem="vn-knife-hanger-washer",
        script_name="draw_vn_knife_hanger_washer.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_lag_screw",
        part="vn_lag_screw",
        artifact_stem="vn-lag-screw",
        script_name="draw_vn_lag_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_arbor_set_screw",
        part="vn_arbor_set_screw",
        artifact_stem="vn-arbor-set-screw",
        script_name="draw_vn_arbor_set_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_pen_set_screw",
        part="vn_pen_set_screw",
        artifact_stem="vn-pen-set-screw",
        script_name="draw_vn_pen_set_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_post_mount_screw",
        part="vn_post_mount_screw",
        artifact_stem="vn-post-mount-screw",
        script_name="draw_vn_post_mount_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_slotted_screw",
        part="vn_slotted_screw",
        artifact_stem="vn-slotted-screw",
        script_name="draw_vn_slotted_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_swing_stop_screw",
        part="vn_swing_stop_screw",
        artifact_stem="vn-swing-stop-screw",
        script_name="draw_vn_swing_stop_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="vn_thumb_screw",
        part="vn_thumb_screw",
        artifact_stem="vn-thumb-screw",
        script_name="draw_vn_thumb_screw.py",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="sm_summing_assembly",
        part="sm_summing",
        artifact_stem="sm-summing-assembly",
        script_name="draw_sm_summing_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ch_channel_assembly",
        part="ch_channel",
        artifact_stem="ch-channel-assembly",
        script_name="draw_ch_channel_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="dt_drive_train_assembly",
        part="dt_drive_train",
        artifact_stem="dt-drive-train-assembly",
        script_name="draw_dt_drive_train_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="fr_frame_assembly",
        part="fr_frame",
        artifact_stem="fr-frame-assembly",
        script_name="draw_fr_frame_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
        additional_layouts=(DrawingLayout.PORTRAIT,),
    ),
    DrawingSpec(
        name="mg_magnifier_assembly",
        part="mg_magnifier",
        artifact_stem="mg-magnifier-assembly",
        script_name="draw_mg_magnifier_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="pd_paper_drive_assembly",
        part="pd_paper_drive",
        artifact_stem="pd-paper-drive-assembly",
        script_name="draw_pd_paper_drive_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
    DrawingSpec(
        name="ha_harmonic_analyzer_assembly",
        part="ha_harmonic_analyzer",
        artifact_stem="ha-harmonic-analyzer-assembly",
        script_name="draw_ha_harmonic_analyzer_assembly.py",
        source_kind="assembly",
        layout=DrawingLayout.LANDSCAPE,
    ),
)

DRAWINGS_BY_NAME = {drawing.name: drawing for drawing in DRAWINGS}

if len(DRAWINGS_BY_NAME) != len(DRAWINGS):
    raise RuntimeError("drawing registry contains duplicate task names")

for _drawing in DRAWINGS:
    if _drawing.source_kind not in ("part", "assembly"):
        raise RuntimeError(
            f"drawing {_drawing.name!r} has unknown source_kind "
            f"{_drawing.source_kind!r}"
        )
