"""The true-ANSI drafting-standard manifest for the project templates.

User ruling 2026-09-26 (decision 3, option A): the drawing and part templates
move from an ISO base named "ANSI" (swDetailingDimensionStandard = 2) to a true
ANSI base (= 1), because only a real ISO -> ANSI re-base prints Y14.5's
"MAX"/"MIN" instead of ISO's "max."/"min." (maxmin-ansi-blast-radius v2, runs
20260926T073039391Z-6da20dda and 20260926T075212560Z-476c1f81).

That re-base moves 35 table rows over 34 drafting preferences (61
preference/option pairs) and 65 text formats. This module lists every one
of them with three values:

* ``as_built``    -- the value in the current ISO-based templates;
* ``iso_to_ansi`` -- the value the re-base itself writes (measured in v2);
* ``target``      -- the value the re-based template must carry.

``decision`` is ``ansi`` where the template takes the ANSI default (arrows,
witness and centre lines, leaders, section arrows) and ``restore`` where it
keeps the as-built value (text heights, so every layout recipe calibrated on
3.5 mm text and 6.35 mm view labels stands). Every other document preference
must read back unchanged from ``as_built``.

SolidWorks-free. The template re-base leaf reads it, writes the ``restore``
rows after the re-base, then reads EVERY preference back against it and fails
loud on any difference. Never set swDraftingStandardAllUppercase* (754/552/538):
it prints nothing different and renames the standard irreversibly (v2, option D).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Kind = Literal["integer", "toggle", "double", "text_format"]
Decision = Literal["ansi", "restore"]
# A text format's value is (CharHeight in metres, CharHeightInPts).
Value = int | bool | float | tuple[float, int]

STANDARD_PREF = 13  # swDetailingDimensionStandard
STANDARD_ISO = 2  # swDetailingStandards_e.swDetailingStandardISO
STANDARD_ANSI = 1  # swDetailingStandards_e.swDetailingStandardANSI
STANDARD_NAME_PREF = 65  # swDetailingDimensionStandardName (string)
# The re-base sequence that printed "MAX" in v2. A bare 13 = 1 on a standard
# already NAMED "ANSI" kept "max." (v1); the rename via ISO is what re-words it.
REBASE_SEQUENCE: tuple[int, ...] = (STANDARD_ISO, STANDARD_ANSI)
FORBIDDEN_TOGGLES = {
    "swDraftingStandardAllUppercaseForDimensionsAndHoleCallouts": 754,
    "swDraftingStandardUppercase": 552,
    "swDetailingAllUpperCase": 538,
}


@dataclass(frozen=True)
class Setting:
    kind: Kind
    name: str
    pref: int
    option: str  # swUserPreferenceOption_e member, or "-" for none
    option_id: int
    as_built: Value
    iso_to_ansi: Value
    target: Value
    decision: Decision
    why: str


SETTINGS: tuple[Setting, ...] = (
    Setting(
        "integer",
        "swDetailingArrowStyleForDimensions",
        16,
        "-",
        0,
        0,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingAuxViewLabels_Label",
        250,
        "-",
        0,
        1,
        2,
        2,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingAuxView_ViewIndication",
        512,
        "-",
        0,
        0,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingChamferDimLeaderStyle",
        154,
        "-",
        0,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingAngleDimension",
        201,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingAngularRunningDimension",
        209,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingArcLengthDimension",
        202,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingAuxiliaryView",
        303,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingBalloon",
        101,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingChamferDimension",
        203,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingDatum",
        102,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingDetailView",
        301,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingDiameterDimension",
        204,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingGeometricTolerance",
        103,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingHoleDimension",
        205,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingLinearDimension",
        206,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingLocationLabel",
        309,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingMiscView",
        308,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingNote",
        104,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingOrdinateDimension",
        207,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingOrthoView",
        304,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingRadiusDimension",
        208,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingRevisionCloud",
        107,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingSectionView",
        302,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingSurfaceFinishSymbol",
        105,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "swDetailingWeldSymbol",
        106,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionStandard",
        13,
        "-",
        0,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingGtolLeaderStyle",
        350,
        "-",
        0,
        1,
        2,
        2,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingLinearForeshortened",
        544,
        "swDetailingLinearDimension",
        206,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingLinearForeshortened",
        544,
        "-",
        0,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingNotesLeaderStyle",
        220,
        "-",
        0,
        1,
        2,
        2,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingSFSymbolLeaderStyle",
        358,
        "-",
        0,
        1,
        2,
        2,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingVirtualSharpStyle",
        41,
        "-",
        0,
        2,
        3,
        3,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swLineFontSectionLineStyle",
        62,
        "-",
        0,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swSheetMetalBendNotesLeaderDisplay",
        490,
        "-",
        0,
        0,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swCollinearChainDimensionArrowHeadTermination",
        796,
        "swDetailingLinearDimension",
        206,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swCollinearChainDimensionArrowHeadTermination",
        796,
        "-",
        0,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingAngularRunningDisplayAsChain",
        502,
        "swDetailingAngularRunningDimension",
        209,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingAngularRunningDisplayAsChain",
        502,
        "-",
        0,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingAnnotationUseBentLeaders",
        375,
        "-",
        0,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingAuxView_SimplifiedDetailed",
        541,
        "-",
        0,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingCenterMarkUseCenterLine",
        192,
        "-",
        0,
        True,
        False,
        False,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingDimBreakAroundArrow",
        155,
        "-",
        0,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingDisplayWithBrokenLeaders",
        42,
        "-",
        0,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingNotesDisplayWithBentLeader",
        54,
        "-",
        0,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingArrowHeight",
        24,
        "-",
        0,
        0.000762,
        0.001016,
        0.001016,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingArrowWidth",
        25,
        "-",
        0,
        0.003556,
        0.003302,
        0.003302,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingBreakLineGap",
        11,
        "-",
        0,
        0.01,
        0.0127,
        0.0127,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingCenterMarkSize",
        12,
        "-",
        0,
        0.0025,
        0.00254,
        0.00254,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingCenterlineExtension",
        10,
        "-",
        0,
        0.002,
        0.00635,
        0.00635,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingDimFontHeight",
        1,
        "-",
        0,
        0.0035,
        0.003175,
        0.0035,
        "restore",
        "dimension text stays 3.5 mm: every layout recipe and keep-out is calibrated on it",
    ),
    Setting(
        "double",
        "swDetailingNoteFontHeight",
        0,
        "-",
        0,
        0.0035,
        0.003175,
        0.0035,
        "restore",
        "note text stays 3.5 mm, the same as the dimension text",
    ),
    Setting(
        "double",
        "swDetailingSectionArrowHeight",
        27,
        "-",
        0,
        0.003,
        0.002032,
        0.002032,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingSectionArrowLength",
        29,
        "-",
        0,
        0.012,
        0.0127,
        0.0127,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingSectionArrowWidth",
        28,
        "-",
        0,
        0.006,
        0.00635,
        0.00635,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingWitnessLineExtension",
        14,
        "-",
        0,
        0.001,
        0.003175,
        0.003175,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "double",
        "swDetailingWitnessLineGap",
        13,
        "-",
        0,
        0.001,
        0.00127,
        0.00127,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionTextAndLeaderStyle",
        372,
        "swDetailingAngularRunningDimension",
        209,
        2,
        3,
        3,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "integer",
        "swDetailingDimensionTextAndLeaderStyle",
        372,
        "swDetailingChamferDimension",
        203,
        2,
        1,
        1,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingDimANSIBentLeader",
        251,
        "swDetailingAngleDimension",
        201,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "toggle",
        "swDetailingDimANSIBentLeader",
        251,
        "swDetailingLinearDimension",
        206,
        False,
        True,
        True,
        "ansi",
        "take the ANSI default",
    ),
    Setting(
        "text_format",
        "swDetailingAnnotationTextFormat",
        19,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingAuxView_DelimiterTextFormat",
        37,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingAuxView_LabelTextFormat",
        34,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingAuxView_NameTextFormat",
        33,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingAuxView_RotationTextFormat",
        35,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingAuxView_ScaleTextFormat",
        36,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingBalloonTextFormat",
        8,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingBendTextFormat",
        22,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingBillOfMaterialTextFormat",
        11,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDatumTextFormat",
        14,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_DelimiterTextFormat",
        45,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_LabelTextFormat",
        43,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_ScaleTextFormat",
        44,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingFamilyTableTextFormat",
        50,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingGeneralTableTextFormat",
        7,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingGeometricToleranceTextFormat",
        15,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingHoleTableTextFormat",
        12,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingLocationLabelTextFormat",
        46,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_DelimiterTextFormat",
        32,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_NameTextFormat",
        30,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_ScaleTextFormat",
        31,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingNoteTextFormat",
        0,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingOrthoView_DelimiterTextFormat",
        41,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingOrthoView_NameTextFormat",
        39,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingOrthoView_ScaleTextFormat",
        40,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingPunchTextFormat",
        27,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingRevisionTableTextFormat",
        13,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionLabelDelimiterTextFormat",
        26,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionLabelLabelTextFormat",
        24,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionLabelScaleTextFormat",
        25,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionView_RotationTextFormat",
        38,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingTableTextFormat",
        17,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingTitleBlockTableTextFormat",
        20,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingViewArrowTextFormat",
        4,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingViewTextFormat",
        18,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swSheetMetalBendNotesTextFormat",
        28,
        "-",
        0,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingBalloonTextFormat",
        8,
        "swDetailingBalloon",
        101,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_DelimiterTextFormat",
        45,
        "swDetailingDetailView",
        301,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_LabelTextFormat",
        43,
        "swDetailingDetailView",
        301,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_ScaleTextFormat",
        44,
        "swDetailingDetailView",
        301,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingAngleDimension",
        201,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingAngularRunningDimension",
        209,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingArcLengthDimension",
        202,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingChamferDimension",
        203,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingDiameterDimension",
        204,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingDimension",
        200,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingHoleDimension",
        205,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingLinearDimension",
        206,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingOrdinateDimension",
        207,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDimensionTextFormat",
        1,
        "swDetailingRadiusDimension",
        208,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingLocationLabelTextFormat",
        46,
        "swDetailingLocationLabel",
        309,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_DelimiterTextFormat",
        32,
        "swDetailingMiscView",
        308,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_NameTextFormat",
        30,
        "swDetailingMiscView",
        308,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingMiscView_ScaleTextFormat",
        31,
        "swDetailingMiscView",
        308,
        (0.0035, 13),
        (0.003175, 12),
        (0.0035, 13),
        "restore",
        "annotation, view and table text keeps its as-built 3.5 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailLabelTextFormat",
        9,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailTextFormat",
        3,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_NameTextFormat",
        42,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionLabelNameTextFormat",
        23,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionLabelTextFormat",
        10,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSectionTextFormat",
        2,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingSurfaceFinishTextFormat",
        5,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingWeldSymbolTextFormat",
        6,
        "-",
        0,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailTextFormat",
        3,
        "swDetailingDetailView",
        301,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
    Setting(
        "text_format",
        "swDetailingDetailView_NameTextFormat",
        42,
        "swDetailingDetailView",
        301,
        (0.00635, 24),
        (0.003175, 12),
        (0.00635, 24),
        "restore",
        "section/detail/weld/surface-finish label keeps its as-built 6.35 mm height",
    ),
)

# The re-base must write EXACTLY these; any other preference it moves is a
# finding, not a tolerance (the leaf fails loud on it).
DISTINCT_SETTINGS = len({(s.kind, s.name) for s in SETTINGS if s.kind != "text_format"})
TEXT_FORMATS = sum(1 for s in SETTINGS if s.kind == "text_format")


def restores() -> tuple[Setting, ...]:
    """The rows the leaf must WRITE after the re-base (target != iso_to_ansi)."""
    return tuple(s for s in SETTINGS if s.target != s.iso_to_ansi)


def key(setting: Setting) -> str:
    """The dump key the blast diag used: ``kind|name|option``."""
    return f"{setting.kind}|{setting.name}|{setting.option}"
