r"""Reproduction script: measuring stick (book ch. 16, pp. 34-37).

Ruled brass gauge (Wm. Gaertner & Co.) used to position the amplitude bars.
The unchanged 0-10 scale spans 142 mm at the configured 14.2 mm pitch.
The longer half-division tick follows the book. The stop is a separate brass
block, cover and stock hardware in the ms-measuring-stick assembly.

The annotated bar is 200 mm long and 8 mm wide; thickness is photo-derived.

Layout: bar along +X with the bottom-left corner on the origin; graduations
engraved 0.5 mm deep into the back face (z=0), tick 0 at x=57.5 so the 10 tick
lands just short of the far end (page001_img02).

Numerals: the 0..10 values are engraved beside their full ticks (page001_img01:
~2 mm sans-serif, turned 90 degrees to read with the 10 end up). There is no
sketch-text API in the adapter, so -- the nameplate precedent -- they come from
a vendored DXF of closed loops, ``cad/references/ms-stick-numerals.dxf``,
GENERATED by ``gen_ms_stick_numerals_dxf.py`` from ``ms_stick_spec`` constants (font
rendering via ``_dxf_text``), imported onto the Front plane at scale 1 /
position (0, 0) (placement is baked into the file: the Makers seat ignores the
importer's scale/position, see ``build_fr_nameplate``) and cut ``TICK_DEPTH`` deep
as one feature. The frame/sign conventions (the z=0 ruled face is SEEN from
-Z, so the file carries a y inversion, never applied at import) are worked out
in the generator's docstring. Edit a ``NUMERAL_*`` knob in ``ms_stick_spec``,
regenerate the DXF and update that spec's area/bounds from the generator output.

Known, accepted (2026-09-02 pass 3): the tick layout is the MIRROR image of the
photographed stick. page001_img01 shows 0 at the left with the ticks hanging from
the FAR long edge; this model's ruled face, seen face-on with 0 at the left (the
drawing's rotated ``*Back`` view), has them hanging from the NEAR edge, because
the tick sketch was drawn in the +Z frame and cut into the z=0 back face. A
plain bar has no other handedness, so it only matters once the stop block's
orientation is tied to the ruled edge; the numerals are laid out in the
as-seen (-Z) frame so they read correctly on the face regardless.

Run only through the supervised farm launcher: ``part:ms_stick``.
"""

from __future__ import annotations

import sys

import _telemetry
from _appearance import apply_material
from _check import check
from _com import _early_bound
from _dimensions import drive_dimension, dump_dimensions, name_dimensions, set_global
from _feature_tree import name_last_feature
from _part_checks import measure_check, report_mass_properties, volume_check
from _part_save import save_part_and_images
from _rebuild import force_rebuild
from _session import run_build
from _sketch import (
    SketchDims,
    add_line_chain,
    anchor_point_to_origin,
    dimension_between,
    ensure_fully_defined,
    set_sketch_direct_db,
)
from _drawing_marks import (
    apply_drawing_properties,
    apply_drawing_precision,
    clear_dimensions_for_drawing,
    mark_dimensions_for_drawing,
    set_dimension_symmetric_tolerance,
)
from ms_stick_geom import (
    DIVISION_COUNT,
    DIVISION_SPACING,
    MINOR_PER_DIVISION,
    MINOR_SPACING,
)
from ms_stick_spec import (
    BODY_LENGTH,
    BODY_WIDTH,
    BODY_THICKNESS,
    DRAWING_DIMENSIONS,
    DRAWING_PRECISION,
    DRAWING_TOLERANCES,
    DRAWING_NOTES,
    SCALE_END_NOTE,
    FRONT_VIEW_NOTE,
    ISOMETRIC_VIEW_NOTE,
    HALF_TICK_LENGTH,
    MINOR_TICK_LENGTH,
    NUMERALS_DXF,
    NUMERAL_HEIGHT_MM,
    NUMERAL_GAP_MM,
    NUMERAL_AREA_MM2,
    REFERENCE_DIMENSIONS,
    SCALE_END_MARGIN,
    SCALE_START_X,
    TICK_WIDTH,
    TICK_LENGTH,
    TICK_DEPTH,
    TICK_OVERHANG,
)
from _visibility import blank_sketch_feature

PART_NAME = "ms-stick"
MATERIAL = "Brass"  # see _appearance.apply_material docstring



async def _cut_tick(
    adapter,
    label: str,
    stem: str,
    x_center: float,
    length: float,
    *,
    drive_jobs: list[tuple[str, str]],
    drive_xcenter: str,
    drive_length: str,
) -> str:
    """Cut one graduation tick; returns the cut feature name.

    Self-naming: ``stem`` makes the sketch/feature/dim names unique per tick
    (the equation manager keys dims by ``leaf@feature``). The four sketch dims
    emit in creation order -- width, length, then the bottom-left corner anchor
    (x then z, both non-zero) -- recorded into a per-tick :class:`SketchDims` and
    driven via the deferred ``drive_jobs`` batch. ``drive_xcenter`` is the
    equation for the tick's centre x; the corner-X dim is an UNSIGNED distance,
    so it drives to that centre minus half the tick width.
    """
    from solidworks_mcp.adapters.base import ExtrusionParameters

    dims = SketchDims()
    check(f"create_sketch {label}", await adapter.create_sketch("Front"))
    half = TICK_WIDTH / 2.0
    top_y = BODY_WIDTH + TICK_OVERHANG
    lines = await add_line_chain(
        adapter,
        [
            (x_center - half, BODY_WIDTH - length),
            (x_center + half, BODY_WIDTH - length),
            (x_center + half, top_y),
            (x_center - half, top_y),
        ],
    )
    bottom, right, top, left = lines
    for ent, relation in (
        (bottom, "horizontal"),
        (top, "horizontal"),
        (right, "vertical"),
        (left, "vertical"),
    ):
        check(
            f"{label} constraint {relation}",
            await adapter.add_sketch_constraint(ent, None, relation),
        )
    check(
        f"{label} width dim",
        await adapter.add_sketch_dimension(bottom, None, "linear", TICK_WIDTH),
    )
    dims.record(f"{stem}Width", '"TickWidth"')
    check(
        f"{label} length dim",
        await adapter.add_sketch_dimension(
            right, None, "linear", length + TICK_OVERHANG
        ),
    )
    dims.record(f"{stem}Length", f'{drive_length} + "TickOverhang"')
    # Corner anchor at (x_center - half, BODY_WIDTH - length): both non-zero, so
    # two dims (x then z). Both are unsigned distances from the origin and both
    # land positive here, so the drives evaluate positive directly.
    await anchor_point_to_origin(
        adapter,
        f"{bottom}.start",
        x_center - half,
        BODY_WIDTH - length,
        f"{label} corner",
    )
    dims.record(f"{stem}CornerX", f'{drive_xcenter} - "TickWidth" / 2')
    dims.record(f"{stem}CornerZ", f'"BodyWidth" - ({drive_length})')
    await ensure_fully_defined(adapter, f"{label} sketch")
    check(f"exit_sketch {label}", await adapter.exit_sketch())
    name_last_feature(adapter, f"{stem}Profile")
    drive_jobs += dims.apply(adapter, f"{stem}Profile")
    cut = await adapter.create_cut_extrude(ExtrusionParameters(depth=TICK_DEPTH))
    check(f"cut {label}", cut)
    return name_last_feature(adapter, f"{stem}Cut")


@_telemetry.traced("sketch.stick_manufacturing_chords")
async def _manufacturing_chords(adapter, drive_jobs: list[tuple[str, str]]) -> None:
    """Bind finished engraving sizes to their knobs, excluding profile overhang.

    The tracked numeral artwork stays fixed. Its gaps therefore measure from
    the editable tick to the original glyph edge, not to an imaginary moved DXF.
    """
    scale_x = '"ScaleStartX"'
    edge_y = '"BodyWidth"'
    glyph_x = SCALE_START_X + TICK_WIDTH / 2.0 + NUMERAL_GAP_MM
    glyph_y = BODY_WIDTH - TICK_LENGTH - NUMERAL_GAP_MM
    bindings = {
        "ScaleStartReference": (scale_x, None, edge_y),
        "FullLengthReference": ('"TickLength"', scale_x, '"BodyWidth" - "TickLength"'),
        "MinorLengthReference": (
            '"MinorTickLength"',
            f'{scale_x} + "DivisionSpacing" / {MINOR_PER_DIVISION}',
            '"BodyWidth" - "MinorTickLength"',
        ),
        "HalfLengthReference": (
            '"HalfTickLength"', f'{scale_x} + "DivisionSpacing" / 2',
            '"BodyWidth" - "HalfTickLength"',
        ),
        "FullPitchReference": ('"DivisionSpacing"', scale_x, edge_y),
        "MinorPitchReference": (
            f'"DivisionSpacing" / {MINOR_PER_DIVISION}', scale_x, edge_y,
        ),
        "NumeralHeightReference": (
            f"{NUMERAL_HEIGHT_MM}mm", f"{glyph_x}mm", f"{glyph_y}mm",
        ),
        "NumeralXGapReference": (
            f'{glyph_x}mm - ({scale_x} + "TickWidth" / 2)',
            f'{scale_x} + "TickWidth" / 2', f"{glyph_y}mm",
        ),
        "NumeralYGapReference": (
            f'"BodyWidth" - "TickLength" - {glyph_y}mm',
            f"{glyph_x}mm", f"{glyph_y}mm",
        ),
    }
    for feature, (name, start, end) in REFERENCE_DIMENSIONS.items():
        dims = SketchDims()
        size_expr, x_expr, y_expr = bindings[feature]
        check(feature, await adapter.create_sketch("Front"))
        set_sketch_direct_db(adapter, True)
        line = check(feature, await adapter.add_line(*start, *end))
        set_sketch_direct_db(adapter, False)
        segment = _early_bound(adapter._sketch_entities[line], "ISketchSegment")
        segment.ConstructionGeometry = True
        if not bool(segment.ConstructionGeometry):
            raise RuntimeError(f"{feature}: construction flag rejected")
        horizontal = start[1] == end[1]
        check(feature, await adapter.add_sketch_constraint(
            line, None, "horizontal" if horizontal else "vertical"))
        await dimension_between(
            adapter, f"{line}.start", f"{line}.end",
            "horizontal_distance" if horizontal else "vertical_distance",
            abs(end[0] - start[0]) if horizontal else abs(end[1] - start[1]),
            feature,
        )
        dims.record(name, size_expr)
        await anchor_point_to_origin(adapter, f"{line}.start", *start, feature)
        if abs(start[0]) >= 1e-9:
            dims.record(f"{name}AnchorX", x_expr)
        if abs(start[1]) >= 1e-9:
            dims.record(f"{name}AnchorY", y_expr)
        await ensure_fully_defined(adapter, feature)
        check(feature, await adapter.exit_sketch())
        name_last_feature(adapter, feature)
        drive_jobs += dims.apply(adapter, feature)


@_telemetry.traced("appearance.stick_manufacturing_chords")
def _hide_manufacturing_chords(adapter) -> None:
    model = _early_bound(adapter.currentModel, "IPartDoc")
    for feature_name in REFERENCE_DIMENSIONS:
        feature = model.FeatureByName(feature_name)
        if feature is None:
            raise RuntimeError(f"missing manufacturing sketch {feature_name}")
        blank_sketch_feature(adapter.currentModel, _early_bound(feature, "IFeature"), feature_name)


async def build(adapter) -> dict[str, str]:
    from solidworks_mcp.adapters.base import (
        ExtrusionParameters,
        ImportDxfDwgParameters,
        LinearPatternParameters,
    )

    check("create_part", await adapter.create_part())

    # Editable knobs (Tools > Equations). The mm suffix is load-bearing -- this is
    # an INCH document and the equation manager reads BARE numbers in document
    # units (an unsuffixed 200 = 200 in, a 25.4x blow-up). ScaleStartX is a
    # DERIVED global (locates the configured scale short of the right end),
    # referencing the others as an equation string. DivisionSpacing drives the
    # FEATURE parameter -- a knob with nothing in the deferred sketch-dim batch,
    # like an extrude depth (matches the exemplars).
    await set_global(adapter, "BodyLength", f"{BODY_LENGTH}mm")
    await set_global(adapter, "BodyWidth", f"{BODY_WIDTH}mm")
    await set_global(adapter, "BodyThickness", f"{BODY_THICKNESS}mm")
    await set_global(adapter, "DivisionSpacing", f"{DIVISION_SPACING}mm")
    await set_global(adapter, "ScaleEndMargin", f"{SCALE_END_MARGIN}mm")
    await set_global(adapter, "TickWidth", f"{TICK_WIDTH}mm")
    await set_global(adapter, "TickLength", f"{TICK_LENGTH}mm")
    await set_global(adapter, "MinorTickLength", f"{MINOR_TICK_LENGTH}mm")
    await set_global(adapter, "HalfTickLength", f"{HALF_TICK_LENGTH}mm")
    await set_global(adapter, "TickOverhang", f"{TICK_OVERHANG}mm")
    await set_global(
        adapter,
        "ScaleStartX",
        f'"BodyLength" - {DIVISION_COUNT - 1} * "DivisionSpacing" - "ScaleEndMargin"',
    )

    drive_jobs: list[tuple[str, str]] = []

    # Body: plain rectangular bar. Two display dims emit in creation order --
    # length then width -- recorded as they are added; the (0, 0) corner anchors
    # by a coincident relation (no dim).
    body_dims = SketchDims()
    check("create_sketch body", await adapter.create_sketch("Front"))
    body = await add_line_chain(
        adapter,
        [(0.0, 0.0), (BODY_LENGTH, 0.0), (BODY_LENGTH, BODY_WIDTH), (0.0, BODY_WIDTH)],
    )
    bottom, right, top, left = body
    for ent, relation in (
        (bottom, "horizontal"),
        (top, "horizontal"),
        (right, "vertical"),
        (left, "vertical"),
    ):
        check(
            f"body constraint {relation}",
            await adapter.add_sketch_constraint(ent, None, relation),
        )
    check(
        "body length dim",
        await adapter.add_sketch_dimension(bottom, None, "linear", BODY_LENGTH),
    )
    body_dims.record("BodyLength", '"BodyLength"')
    check(
        "body width dim",
        await adapter.add_sketch_dimension(right, None, "linear", BODY_WIDTH),
    )
    body_dims.record("BodyWidth", '"BodyWidth"')
    # Pin the (0, 0) corner to the origin. The h/v relations + the two dims fix
    # the bar's shape but not its position; that corner was previously located
    # only by SolidWorks snapping it onto the origin during the (inference-on)
    # line draw -- a crutch removed now that add_line_chain suppresses inference.
    check(
        "body corner -> origin",
        await adapter.add_sketch_constraint(f"{bottom}.start", "origin", "coincident"),
    )
    await ensure_fully_defined(adapter, "body sketch")
    check("exit_sketch body", await adapter.exit_sketch())
    name_last_feature(adapter, "BodyProfile")
    drive_jobs += body_dims.apply(adapter, "BodyProfile")
    check(
        "extrude body",
        await adapter.create_extrusion(ExtrusionParameters(depth=BODY_THICKNESS)),
    )
    name_last_feature(adapter, "Body")
    # Drive the body's extrude depth from BodyThickness too (D1 is the blind-
    # extrude depth dim) so the thickness knob is live, not inert. As-built ->
    # neutral.
    name_dimensions(adapter, "Body", ["BodyThickness"])
    drive_jobs.append(("BodyThickness@Body", '"BodyThickness"'))

    # Tick 0 (seed) + linear pattern for ticks 1..10. The seed cut is RENAMED
    # ("Tick0Cut"), so the pattern must seed off the NEW name -- a captured
    # auto-name would go stale the moment name_last_feature ran (M: renamed-feature
    # references). _cut_tick returns the assigned name for exactly this reason.
    seed_name = await _cut_tick(
        adapter,
        "tick 0",
        "Tick0",
        SCALE_START_X,
        TICK_LENGTH,
        drive_jobs=drive_jobs,
        drive_xcenter='"ScaleStartX"',
        drive_length='"TickLength"',
    )
    name_dimensions(adapter, "Tick0Cut", ["TickDepth"])
    check(
        "linear pattern ticks 1..10",
        await adapter.linear_pattern_feature(
            LinearPatternParameters(
                direction_point=[BODY_LENGTH / 2.0, 0.0, 0.0],
                direction_vector=[1.0, 0.0, 0.0],
                features=[seed_name],
                count=DIVISION_COUNT,
                spacing=DIVISION_SPACING,
            )
        ),
    )
    name_last_feature(adapter, "TickPattern")
    # Drive the pattern's spacing from DivisionSpacing too. The seed (Tick0) and
    # half-tick are driven from ScaleStartX (DivisionSpacing-derived), so the
    # pattern's own spacing dim MUST track DivisionSpacing or ticks 1..10 keep
    # the old 8 mm pitch and the ruled scale corrupts on a GUI edit (the Codex
    # P2). The spacing is D3 (verified by dump_dimensions: D1 is the pattern's
    # ~11000 mm direction-reference length, NOT the pitch); D3 == as-built 8 mm,
    # so it stays neutral.
    drive_jobs.append(("D3@TickPattern", '"DivisionSpacing"'))

    # Tenths: nine short ticks between the 0 and 1 full ticks, cut one by one
    # (each drives off ScaleStartX + k * DivisionSpacing / 10), then the nine
    # patterned as a group across the other nine divisions. (A pattern of the
    # minor pattern would need two nested pattern features; nine seed cuts +
    # one pattern keeps every feature a plain cut or pattern.) The pattern's
    # own spacing dim is driven from DivisionSpacing below, resolved by VALUE
    # rather than by the D3 index (CodeRabbit #651: a static pitch would
    # leave the patterned tenths at 14.2 after a GUI DivisionSpacing edit).
    minor_names = []
    for k in range(1, MINOR_PER_DIVISION):
        minor_names.append(
            await _cut_tick(
                adapter,
                f"minor tick 0.{k}",
                f"Minor{k}",
                SCALE_START_X + k * MINOR_SPACING,
                MINOR_TICK_LENGTH,
                drive_jobs=drive_jobs,
                drive_xcenter=f'"ScaleStartX" + {k} * "DivisionSpacing" / {MINOR_PER_DIVISION}',
                drive_length='"MinorTickLength"',
            )
        )
    check(
        "linear pattern minor ticks across divisions 1..9",
        await adapter.linear_pattern_feature(
            LinearPatternParameters(
                direction_point=[BODY_LENGTH / 2.0, 0.0, 0.0],
                direction_vector=[1.0, 0.0, 0.0],
                features=minor_names,
                count=DIVISION_COUNT - 1,
                spacing=DIVISION_SPACING,
            )
        ),
    )
    name_last_feature(adapter, "MinorPattern")
    # The pattern's dims are the direction-reference length (~11000 mm), the
    # count and the pitch; the one reading the as-built pitch is unambiguous.
    minor_pitch_dims = [
        row["full_name"]
        for row in dump_dimensions(adapter, "MinorPattern")
        if abs(row["value_mm"] - DIVISION_SPACING) < 1e-3
    ]
    if len(minor_pitch_dims) != 1:
        raise RuntimeError(
            f"MinorPattern: expected one dim reading the {DIVISION_SPACING} pitch, "
            f"found {minor_pitch_dims}"
        )
    drive_jobs.append((minor_pitch_dims[0], '"DivisionSpacing"'))

    # The hand-stamped artefact the book calls out: a longer 0.5 tick (it
    # overcuts the 0.5 tenth above).
    await _cut_tick(
        adapter,
        "tick 0.5",
        "TickHalf",
        SCALE_START_X + DIVISION_SPACING / 2.0,
        HALF_TICK_LENGTH,
        drive_jobs=drive_jobs,
        drive_xcenter='"ScaleStartX" + "DivisionSpacing" / 2',
        drive_length='"HalfTickLength"',
    )

    # Numerals 0..10: import the generated DXF (closed loops at final model mm,
    # already y-inverted to read correctly on the z=0 face seen from -Z -- see
    # gen_ms_stick_numerals_dxf) onto the Front plane and cut TICK_DEPTH into +Z,
    # the same direction and depth as every tick. Imported at identity
    # placement because the Makers seat ignores SetPosition/SetSheetScale
    # (build_fr_nameplate); scale/position are passed as (1, (0, 0)) as a
    # statement of intent, not a control. No dims to drive: the numerals are
    # not parametric, so this feature stays out of drive_jobs and, cut before
    # the v_built capture below, out of the neutrality proof's way.
    if not NUMERALS_DXF.is_file():
        raise RuntimeError(f"numerals DXF not found: {NUMERALS_DXF}")
    pre = await adapter.get_mass_properties()
    if not pre.is_success:
        raise RuntimeError(f"measuring stick: get_mass_properties failed: {pre.error}")
    check(
        "import numerals DXF",
        await adapter.import_dxf_dwg(
            ImportDxfDwgParameters(
                file_path=str(NUMERALS_DXF),
                plane="Front",
                scale=1.0,
                position=[0.0, 0.0],
                merge_points=True,  # closed LWPOLYLINEs -> closed regions
                import_hatch=False,
                import_dimensions=False,
                add_constraints=False,
            )
        ),
    )
    name_last_feature(adapter, "NumeralsSketch")
    check(
        "cut numerals",
        await adapter.create_cut_extrude(ExtrusionParameters(depth=TICK_DEPTH)),
    )
    name_last_feature(adapter, "Numerals")
    post = await adapter.get_mass_properties()
    if not post.is_success:
        raise RuntimeError(f"measuring stick: get_mass_properties failed: {post.error}")
    removed = float(pre.data.volume) - float(post.data.volume)
    expected = NUMERAL_AREA_MM2 * TICK_DEPTH
    _telemetry.info(
        f"numerals cut removed {removed:.3f} mm^3 (DXF loops {NUMERAL_AREA_MM2:.3f} mm^2 "
        f"x {TICK_DEPTH} = {expected:.3f})"
    )
    # 25 %: the loops clear every tick (no shared volume, pinned by test_dxf_text),
    # so the cut is area x depth up to the importer's curve fitting and the
    # sketch-region merge; a mirrored/offset import that misses the face, a
    # stale DXF or a wrong plane lands far outside this band.
    if abs(removed - expected) > 0.25 * expected:
        raise RuntimeError(
            f"cut numerals: removed {removed:.3f} mm^3, expected {expected:.3f} "
            f"+/-25% -- check the DXF import plane/placement or re-pin NUMERAL_AREA_MM2"
        )

    await apply_material(adapter, MATERIAL)

    # Capture the as-built volume, then apply the deferred drive equations and
    # re-check: every equation evaluates to the value just built, so the geometry
    # must not move (the neutrality proof; this part's other checks are measures).
    mass = await adapter.get_mass_properties()
    if not mass.is_success:
        raise RuntimeError(f"measuring stick: get_mass_properties failed: {mass.error}")
    v_built = float(mass.data.volume)
    await _manufacturing_chords(adapter, drive_jobs)
    await force_rebuild(adapter)
    for dim_name, expr in drive_jobs:
        await drive_dimension(adapter, dim_name, expr)
    await force_rebuild(adapter)
    await volume_check(
        adapter, "driven measuring-stick (equations neutral)", v_built, 0.005 * v_built
    )

    # Verify the annotated 200 mm length and the untouched front face
    # (the 14.2 mm tick spacing is driven by the linear pattern's spacing).
    # End faces are edge-on in the active view (point picking is
    # screen-projected) — measure the uncut front-bottom edge instead;
    # the ticks only engrave the back face from the top edge down.
    mid_y = BODY_WIDTH / 2.0
    await measure_check(
        adapter,
        "body length (annotated 200)",
        [{"entity_type": "EDGE", "point": [BODY_LENGTH / 2.0, 0.0, BODY_THICKNESS]}],
        "length",
        BODY_LENGTH,
    )
    await measure_check(
        adapter,
        "front face area (ticks cut the back face only)",
        [
            {
                "entity_type": "FACE",
                "point": [BODY_LENGTH / 2.0, mid_y, BODY_THICKNESS],
            }
        ],
        "area",
        BODY_LENGTH * BODY_WIDTH,
        tol=1.0,
    )

    await report_mass_properties(adapter)
    for feature, names in DRAWING_DIMENSIONS.items():
        for name in names:
            if name in DRAWING_TOLERANCES:
                set_dimension_symmetric_tolerance(
                    adapter, feature, name, DRAWING_TOLERANCES[name])
    clear_dimensions_for_drawing(adapter)
    for feature_name, dimension_names in DRAWING_DIMENSIONS.items():
        mark_dimensions_for_drawing(adapter, feature_name, dimension_names)
    apply_drawing_precision(adapter, DRAWING_PRECISION)
    apply_drawing_properties(
        adapter,
        PART_NAME,
        {
            "Manufacturing Notes": DRAWING_NOTES,
            "Front View Note": FRONT_VIEW_NOTE,
            "Isometric View Note": ISOMETRIC_VIEW_NOTE,
            "Scale End Note": SCALE_END_NOTE,
        },
    )
    _hide_manufacturing_chords(adapter)
    return await save_part_and_images(adapter, PART_NAME)


if __name__ == "__main__":
    sys.exit(run_build(build))
