r"""Create the curated machinist drawing for the platen guide.

The SLDPRT remains authoritative.  This recipe supplies only the platen-guide
views, dimensions, hole groups, and manufacturing notes; shared sheet/template,
leader, reopen, and artifact behavior lives in ``_drawing_common``.

The print is deliberately plain (cad/docs/drawing-simplicity-policy.md): a
drilled and tapped guide bar carries no datums, frames or roughness symbols;
the native hole table gives every station under the title block's general
tolerance and the SIZE column carries each hole's wizard callout.  The SIZE
cells are SolidWorks-generated from the Hole Wizard callout format (no process
word), so one note directly under the table states the process for every row.

Run with SolidWorks open::

    uv run python cad\scripts\draw_platen_guide.py platen-guide
"""

from __future__ import annotations

import argparse
import sys
from typing import Any

import _telemetry
from _common import CAD_ROOT, check, run_build
from _drawing_common import (
    DrawingOutputs,
    add_property_linked_note,
    curate_view_dimensions,
    finalize_drawing,
    import_cosmetic_threads,
    insert_hole_table,
    new_project_drawing,
    read_required_properties,
    set_hidden_lines_removed,
    set_hidden_lines_visible,
    stamp_drawing_summary,
)
from _drawing_registry import DRAWINGS_BY_NAME
from build_platen_guide import GUIDE_LENGTH
from build_platen_guide import HOLE_X as THROUGH_X
from build_platen_guide import SCREW_STATION_X as BLIND_X
from solidworks_mcp.adapters.solidworks.drawing import (
    add_note,
    auto_center_marks,
    place_view,
    remove_notes_matching,
)


SPEC = DRAWINGS_BY_NAME["platen_guide"]
PART_STEM = SPEC.artifact_stem
SOURCE = CAD_ROOT / "out" / "sldprt" / f"{PART_STEM}.SLDPRT"
OUTPUTS = DrawingOutputs(
    slddrw=SPEC.outputs["slddrw"],
    pdf=SPEC.outputs["pdf"],
    png=SPEC.outputs["png"],
)
SLDDRW = OUTPUTS.slddrw
PDF = OUTPUTS.pdf
PNG = OUTPUTS.png

# The 1:1 front view is centred at sheet X=0.190 m. Derive its left edge from
# the resized guide so the hole-table anchors follow the part geometry.
FRONT_VIEW_X_M = 0.190
FRONT_LEFT_X_M = FRONT_VIEW_X_M - GUIDE_LENGTH / 2000.0
FRONT_VIEW_Y_M = 0.110
FRONT_HOLE_Y_M = 0.1111
FRONT_BOTTOM_Y_M = FRONT_HOLE_Y_M - 0.0025
# 0.020: the table's left edge lands ~0.3 mm right of its anchor (measured). The
# bound is the 12.7 mm zone margin (~0.0127) the audit checks, which the
# re-centred frame rule now matches (~0.0126); 0.020 keeps the edge clear of both.
HOLE_TABLE_X_M = 0.020
HOLE_TABLE_Y_M = 0.258
# The table's ten rows (header + nine holes) end at y~0.169 (measured on the
# rendered sheet); the process note sits just under that, left-aligned on the
# table's own anchor so it reads as part of the table.  The SIZE cells are
# generated by SolidWorks from the Hole Wizard callout format and
# ``insert_hole_table`` carries no process prefix (unlike
# ``add_native_hole_callout(process=...)``), so the process is stated once here
# for every row (drawing-simplicity-policy.md rule 7: say drill or ream).
HOLE_TABLE_NOTE = "ALL HOLES DRILLED."
HOLE_TABLE_NOTE_Y_M = 0.160
THREAD_DESIGNATION = "#4-40 UNC"
THREAD_MAJOR_DIA_MM = 2.845
THREAD_PITCH_MM = 25.4 / 40.0
THREAD_TAP_DRILL_MM = 2.261


async def build(adapter: Any) -> dict[str, str]:
    if not SOURCE.is_file():
        raise FileNotFoundError(f"source part is missing: {SOURCE}")

    check("open platen-guide source", await adapter.open_model(str(SOURCE)))
    source_model = adapter.currentModel
    read_required_properties(
        source_model,
        (
            "Number",
            "Revision",
            "Title",
            "Material Specification",
            "Finish",
            "Quantity",
            "Manufacturing Notes",
        ),
        required=(
            "Number",
            "Material Specification",
            "Finish",
            "Quantity",
            "Manufacturing Notes",
        ),
    )
    drawing_model, sheet = new_project_drawing(adapter, property_view=PART_STEM)
    stamp_drawing_summary(
        adapter,
        drawing_model,
        {
            0: "Platen Guide Manufacturing Drawing",
            1: "Harmonic Analyzer hobby-machinist book drawing",
            2: "Harmonic Analyzer Project",
            3: "platen guide; manufacturing drawing; #4-40 UNC",
            4: "Generated from the project-owned ASME B drawing standard",
        },
    )
    front = place_view(
        adapter, str(SOURCE), "*Front", FRONT_VIEW_X_M, FRONT_VIEW_Y_M, scale=(1, 1)
    )
    right = place_view(adapter, str(SOURCE), "*Right", 0.370, 0.110, scale=(1, 1))
    # The guide drawn isometrically at the 1:1 sheet scale fills most of the
    # so this view's outline nearly fills the sheet's upper half: at y=0.210 its
    # top ran 11.2 mm into the 12.7 mm zone band. Dropped to 0.196 (~2.8 mm of
    # top clearance). It cannot shrink instead -- a view at a scale other than
    # the sheet's must be labelled, and the only note helpers are property-linked
    # (this part declares no "Isometric View Note"); nor move left (the hole
    # table ends at x=0.159) or right (its box already reaches x~0.410 against
    # the 0.4191 margin).
    iso = place_view(adapter, str(SOURCE), "*Isometric", 0.285, 0.196, scale=(1, 1))
    set_hidden_lines_removed(adapter, iso)
    # Hidden lines ON in every orthographic view: the right view shows the
    # blind tapped holes' depth in the 10 mm section.
    for view in (front, right):
        set_hidden_lines_visible(adapter, view)

    thread_seeds, thread_instances = import_cosmetic_threads(adapter, front)
    expected_thread_instances = len(BLIND_X)
    if thread_instances != expected_thread_instances:
        raise RuntimeError(
            f"front view has {thread_seeds} cosmetic-thread seed(s) / "
            f"{thread_instances} instance(s); expected {expected_thread_instances}"
        )
    removed_thread_notes = remove_notes_matching(adapter, "#4-40")
    _telemetry.info(
        f"front view imported {thread_seeds} cosmetic-thread seed(s) as "
        f"{thread_instances} instance(s); removed {removed_thread_notes} "
        "automatic callout note(s)"
    )

    # Keep only overall length; hole coordinates live in the native hole table.
    curate_view_dimensions(
        adapter, front, keep={"Length": (FRONT_VIEW_X_M, 0.135)}, view_label="front"
    )
    curate_view_dimensions(
        adapter,
        right,
        keep={"Depth": (0.370, 0.095), "Height": (0.385, 0.110)},
        view_label="right",
    )
    if not auto_center_marks(adapter, front, holes=True, size=0.0025):
        raise RuntimeError("failed to add ASME center marks to front view")

    stations = tuple(sorted((*THROUGH_X, *BLIND_X)))
    insert_hole_table(
        adapter,
        front,
        datum_xy=(FRONT_LEFT_X_M, FRONT_BOTTOM_Y_M),
        hole_points=tuple(
            (FRONT_LEFT_X_M + station / 1000.0, FRONT_HOLE_Y_M) for station in stations
        ),
        # X LOC = the station from the left end face; Y LOC = the bar's
        # hole-line height above the bottom face, a constant 2.50.
        expected_locations_mm=tuple(
            (
                station,
                (FRONT_HOLE_Y_M - FRONT_BOTTOM_Y_M) * 1000.0,
            )
            for station in stations
        ),
        anchor_xy=(HOLE_TABLE_X_M, HOLE_TABLE_Y_M),
        # Ordinary X LOC / Y LOC headers: the title-block tolerance governs
        # every station (no position frame to feed a basic box).
        basic_locations=False,
        label="platen-guide",
    )
    # The process for every SIZE row, directly under the table (add_note only
    # warns on failure, so fail loud here: a sheet without it ships a table
    # that never says drill).
    if add_note(adapter, HOLE_TABLE_NOTE, HOLE_TABLE_X_M, HOLE_TABLE_NOTE_Y_M) is None:
        raise RuntimeError("failed to add the hole-table process note")

    # x=0.020: a note is left-aligned on its anchor, so the ink starts here. The
    # bound is the 12.7 mm zone margin (~0.0127), which the re-centred frame rule
    # now matches (~0.0126); 0.020 clears both, and the audit enforces it.
    add_property_linked_note(adapter, "Manufacturing Notes", 0.020, 0.075)

    return await finalize_drawing(
        adapter, OUTPUTS, pdf_title="Platen Guide Manufacturing Drawing"
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("part", choices=[PART_STEM])
    return parser.parse_args()


if __name__ == "__main__":
    _parse_args()
    _telemetry.set_service("drawing-export")
    sys.exit(run_build(build))
