"""Drawing-only text derived from the shared finished-pivot acceptance limits."""

import rod_pivot_spec as pivot

DRAWING_NOTES = (
    "ONE-HEADED BLANK SHOWN BEFORE ASSEMBLY.\n"
    "SUPPORT BOTH FORK CHEEKS WHILE PEENING; DO NOT CLOSE THE SLOT.\n"
    "REJECT CRACKED OR DISCONTINUOUS RETAINING HEADS."
)
JOURNAL_CALLOUT = (
    "MATCH ROCKER ARM MHA-071 BORE\n"
    f"{pivot.PIN_DIAMETRAL_CLEARANCE[0]:.3f}–{pivot.PIN_DIAMETRAL_CLEARANCE[1]:.3f} "
    "DIAMETRAL CLEARANCE"
)
BLANK_LENGTH_CALLOUT = (
    "GRIP MATCHED TO FINISHED\n"
    "CONNECTING ROD MHA-017 OUTER FORK WIDTH;\n"
    "ADD PREFORMED HEAD AND UPSET STOCK"
)
UPSET_CALLOUT = "UPSET STOCK BEYOND MATCHED GRIP"
HEAD_DIAMETER_CALLOUT = (
    f"FINAL RETAINING RIM Ø{pivot.PIN_HEAD_DIAMETER_MIN:.2f} MIN\n"
    f"{pivot.PIN_HEAD_RADIAL_OVERLAP_MIN:.2f} MIN RADIAL OVERLAP\n"
    "BEYOND FINISHED FORK BORE — BOTH HEADS"
)
HEAD_RIM_CALLOUT = (
    f"{pivot.PIN_HEAD_RIM_THICKNESS_MIN:.2f} MIN CONTINUOUS\n"
    "BEARING-RIM THICKNESS — BOTH HEADS"
)
ASSEMBLY_CALLOUT = (
    "INSTALLED STATE — PEEN SECOND HEAD AT ASSEMBLY\n"
    "CONNECTING ROD MHA-017 / ROCKER ARM MHA-071\n"
    f"FINAL SIDEPLAY {pivot.JOINT_ENDFLOAT_MIN:.2f}–{pivot.JOINT_ENDFLOAT_MAX:.2f}; "
    "ROCKER MUST PIVOT FREELY\n"
    f"MAX AXIAL ENVELOPE = STATION PITCH LESS {pivot.PIN_NEIGHBOR_CLEARANCE_MIN:.2f}"
)
