r"""Seed doit's incremental build from a published release bundle.

The CAD artefacts (``.SLDPRT`` / ``.SLDASM``) are gitignored and normally
regenerated by SolidWorks via the COM spine -- ~25 min for the 75 parts plus
~500 s per assembly. A *release* already ships those exact files (the
Pack-and-Go ``solidworks/`` folder, dashed names that match doit's targets), so
on a fresh checkout -- or a machine without a SolidWorks seat -- we can lay the
release files into ``cad/out`` and tell doit they are already built. ``doit
build`` then rebuilds only what changed since the release.

Usage (run with the RELEASE's source checked out -- see the contract below)::

    uv run python cad/scripts/seed_from_release.py harmonic-analyzer-v0.8.0.zip
    uv run python cad/scripts/seed_from_release.py v0.8.0   # fetch via gh

What it does:

  1. Resolve the bundle (a local ``.zip`` or a ``vX.Y.Z`` tag fetched with gh).
  2. Read ``PROVENANCE.json`` from the bundle and assert the current ``git HEAD``
     matches the commit it was built from -- otherwise ``reset-dep`` would record
     the WRONG (current) source as the built-state and doit would skip parts that
     genuinely changed, shipping stale geometry. ``--force`` overrides.
  3. Extract ``solidworks/*.SLDPRT`` -> ``cad/out/sldprt`` and ``*.SLDASM`` ->
     ``cad/out/sldasm``.
  4. ``doit reset-dep`` -- record the present targets' file_dep state as built.
  5. For each assembly with a seeded ``.SLDASM``: write the recipe sidecar that
     ``build_or_refresh`` reads, and inject ``_recipe_digest`` into the doit DB so
     the ``_RecipeTracker`` uptodate recognises it (reset-dep alone does neither,
     so without this every assembly does a needless FULL re-insert).

Contract: run this with the release commit checked out. Then check out your
target branch and ``doit build``; doit rebuilds exactly the source delta. Parts
the top assembly does not reference (orphans) and the base channel springs are
NOT in a Pack-and-Go bundle, so they always rebuild -- reported at the end.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

REPO_ROOT = Path.cwd()
SCRIPTS_DIR = REPO_ROOT / "cad" / "scripts"
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(SCRIPTS_DIR))

import dodo  # noqa: E402  -- the build graph + recipe helpers (CAD_OUT, digests)
from _buildgraph import ASSEMBLY_ORDER, part_stems  # noqa: E402

CAD_OUT = dodo.CAD_OUT
_TAG_RE = re.compile(r"^v\d+\.\d+\.\d+$")
_VALUE_KEY = "_values_:"  # doit's per-task value bucket (note the trailing colon)


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=str(REPO_ROOT), capture_output=True, text=True, check=True
    ).stdout.strip()


def resolve_bundle(arg: str, tmp: Path) -> Path:
    """A local .zip path as-is, or a vX.Y.Z tag downloaded via gh into ``tmp``."""
    if _TAG_RE.match(arg):
        print(f">>  downloading release {arg} via gh ...")
        subprocess.run(
            ["gh", "release", "download", arg, "-p", "*.zip", "--clobber", "-D", str(tmp)],
            cwd=str(REPO_ROOT), check=True,
        )
        zips = sorted(tmp.glob("*.zip"))
        if not zips:
            raise SystemExit(f"!!  no .zip asset on release {arg}")
        return zips[0]
    zip_path = Path(arg)
    if not zip_path.is_file():
        raise SystemExit(f"!!  not a .zip or a vX.Y.Z tag: {arg!r}")
    return zip_path


def check_provenance(zf: zipfile.ZipFile, force: bool) -> str:
    """Assert HEAD == the bundle's build commit (the load-bearing safety gate)."""
    try:
        prov = json.loads(zf.read("PROVENANCE.json"))
        commit = prov["git"]["commit"]
    except (KeyError, json.JSONDecodeError):
        if force:
            print("!!  bundle has no usable PROVENANCE.json -- proceeding (--force)")
            return "?"
        raise SystemExit("!!  bundle has no usable PROVENANCE.json (use --force to skip)")
    head = _git("rev-parse", "HEAD")
    if commit != head and not force:
        raise SystemExit(
            f"!!  HEAD {head[:12]} != bundle commit {commit[:12]}.\n"
            f"    Check out the release commit before seeding (reset-dep records the\n"
            f"    CHECKED-OUT source as the built-state). Override with --force.")
    tag = "matches HEAD" if commit == head else f"DIFFERS from HEAD (forced)"
    print(f">>  bundle commit {commit[:12]} {tag}")
    return commit


def extract_solidworks(zf: zipfile.ZipFile) -> tuple[int, int]:
    """Extract the native Pack-and-Go files into cad/out/sldprt and sldasm."""
    sldprt = CAD_OUT / "sldprt"
    sldasm = CAD_OUT / "sldasm"
    sldprt.mkdir(parents=True, exist_ok=True)
    sldasm.mkdir(parents=True, exist_ok=True)
    parts = asms = 0
    for name in zf.namelist():
        if not name.startswith("solidworks/") or name.endswith("/"):
            continue
        fn = Path(name).name
        dst = (sldasm if fn.endswith(".SLDASM") else sldprt) / fn
        with zf.open(name) as src, open(dst, "wb") as out:
            shutil.copyfileobj(src, out)
        if fn.endswith(".SLDASM"):
            asms += 1
        else:
            parts += 1
    print(f">>  extracted {parts} .SLDPRT + {asms} .SLDASM into cad/out")
    return parts, asms


def reset_dep() -> None:
    """Record the present targets' file_dep state as the last successful build."""
    print(">>  doit reset-dep (record seeded targets as built) ...")
    subprocess.run([sys.executable, "-m", "doit", "reset-dep"], cwd=str(REPO_ROOT), check=True)


def seed_assemblies() -> list[str]:
    """Write recipe sidecars + inject _recipe_digest so assemblies are recognised.

    Returns the stems that could be seeded (those with a present .SLDASM and a
    reset-dep'd task entry). Assemblies referencing a part absent from the bundle
    have a missing file_dep, so reset-dep never recorded them -- they stay stale.
    """
    db_path = CAD_OUT / ".doit.db"
    db = json.loads(db_path.read_text(encoding="utf-8"))
    seeded = []
    for stem in ASSEMBLY_ORDER:
        sldasm = Path(dodo._sldasm(stem))
        if not sldasm.exists():
            continue
        digest = dodo._digest_files(dodo._recipe_files(stem))
        sidecar = dodo._recipe_sidecar(stem)
        sidecar.parent.mkdir(parents=True, exist_ok=True)
        sidecar.write_text(digest + "\n", encoding="utf-8")
        key = f"assembly:{stem}"
        if key in db:
            db[key].setdefault(_VALUE_KEY, {})["_recipe_digest"] = digest
            seeded.append(stem)
    db_path.write_text(json.dumps(db), encoding="utf-8")
    print(f">>  seeded {len(seeded)} assemblies (sidecar + _recipe_digest)")
    return seeded


def report(bundle_parts: set[str]) -> None:
    """What will still rebuild: parts the bundle never contained."""
    want = {s.replace("_", "-") for s in part_stems()}
    missing = sorted(want - bundle_parts)
    if not missing:
        print(">>  every part in the graph was seeded from the bundle")
        return
    print(f">>  {len(missing)} part(s) absent from the bundle -> will rebuild "
          f"(orphans / superseded variants):")
    for m in missing:
        print(f"      {m}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Seed doit's incremental build from a release bundle.")
    ap.add_argument("bundle", help="a local harmonic-analyzer-vX.Y.Z.zip or a vX.Y.Z tag")
    ap.add_argument("--force", action="store_true",
                    help="skip the HEAD==bundle-commit safety check")
    opts = ap.parse_args()

    with tempfile.TemporaryDirectory() as td:
        zip_path = resolve_bundle(opts.bundle, Path(td))
        with zipfile.ZipFile(zip_path) as zf:
            check_provenance(zf, opts.force)
            bundle_parts = {Path(n).stem for n in zf.namelist()
                            if n.startswith("solidworks/") and n.endswith(".SLDPRT")}
            extract_solidworks(zf)

    reset_dep()
    seed_assemblies()
    report(bundle_parts)
    print("\nDone. Now check out your target branch and `uv run python -m doit` -- "
          "doit rebuilds only the source delta since the release.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
