r"""Pure-data dimensional contract shared by the top-frame casting and drawing.

PURE DATA, no SolidWorks/COM imports.  ``build_top_frame`` imports the marked-
dimension NAME map + notes from here; ``draw_top_frame`` keeps exactly
``DRAWING_DIMENSIONS`` and imports the casting's plan geometry (column stations,
bore diameters) from ``build_top_frame`` for its view math.
"""

from __future__ import annotations


# --- Marked-dimension contract: feature -> the parametric dimension NAMES the
# print shows. The two crossed slabs carry the outer envelope; limits and the
# datum-controlled bore pattern stay together in the notes rather than being
# duplicated by isolated native diameter dimensions. ---
DRAWING_DIMENSIONS: dict[str, set[str]] = {
    "SlabAProfile": {"Width"},
    "SlabBProfile": {"Depth"},
}

DRAWING_NOTES = "\n".join(
    (
        "1. MACHINE FROM SOLID STOCK TO FINISHED PROFILE; NO DRAFT OR CAST FILLETS.",
        "2. PLAN PROFILE: 441.60 X 269.00 OUTER RAIL RING; 373.60 X 201.00 CLEAR",
        "   OPENING. RAILS 34.00 +/-0.10 WIDE; OUTER CORNERS R17.00 TANGENT TO BOTH",
        "   RAIL FACES AND CONCENTRIC WITH THE BORES. NO BLENDS OR",
        "   CHAMFERS AT CORNER/RAIL INTERSECTIONS. THESE EDGES ARE EXEMPT FROM",
        "   THE TITLE-BLOCK EDGE BREAK; LEAVE SHARP, 0.25 MAX ROOT RADIUS. ENVELOPE",
        "   441.60 +/-0.25 X 269.00 +/-0.25 X 41.00 +/-0.10; CORNER PADS 47.00 TOTAL,",
        "   6.00 PROUD BELOW THE RAIL UNDERSIDE.",
        "3. WEBBED RAIL SECTION: 10.00 TOP FLANGE AND 5.00 BOTTOM FLANGE AT FULL",
        "   34.00 WIDTH; 26.00 WEB 16.00 THICK, RELIEVED 9.00 PER FACE. THE RELIEF",
        "   STOPS 8.00 CLEAR OF EACH CORNER PAD AND IS INTERRUPTED AT FULL SECTION",
        "   BY THE CROSS RIB AND THE GOOSENECK SOCKET BOSS.",
        "4. CROSS RIB INTEGRAL WITH THE RING: 22.00 WIDE, FULL 41.00 DEEP, TOP FACE",
        "   FLUSH WITH THE RAIL TOP, ON A BASIC 15.00 OFFSET FROM THE FRAME",
        "   CENTRELINE. UNDERSIDE FLAT Ra 3.2 - IT CARRIES THE KNIFE MOUNT.",
        "5. DATUM A = BOTTOM FACE; B = LEFT OUTER RAIL FACE; C = LOWER OUTER RAIL FACE.",
        "   LOWER-LEFT BORE AXIS BASIC 17.00 FROM B/C; OTHERS ON 407.60 X 235.00 BASIC PITCH.",
        "6. COLUMN BORES 4X <MOD-DIAM>25.50 +0.05/0 THRU; POSITION <MOD-DIAM>0.20 A|B|C.",
        "7. CORNER PADS 4X <MOD-DIAM>34.00 +/-0.10; DIMENSIONS/GD&T APPLY BEFORE COATING.",
        "   PAD OD/BORE COAXIALITY AND WALL CHECK: SEE INSPECTION NOTES.",
        "8. GOOSENECK BORE <MOD-DIAM>17.00 +0.20/0 THRU THE SOCKET BOSS; AXIS BASIC ON",
        "   LEFT COLUMN-BORE CENTRELINE, MIDWAY BETWEEN LEFT BORE AXES; POSITION",
        "   <MOD-DIAM>0.20 A|B|C. ALL BORES Ra 1.6.",
        "9. SET SCREW: DRILL <MOD-DIAM>5.11 AND TAP 1/4-20 UNC THRU THE OUTER RAIL",
        "   FACE INTO THE GOOSENECK BORE, AXIS PERPENDICULAR TO B ON THE BORE",
        "   CENTRELINE AT MID-HEIGHT. BREAK THE BREAKOUT EDGE INSIDE THE BORE.",
        "10. MASK DATUM A/B/C FACES, ALL BORES, THE CROSS-RIB UNDERSIDE, 4X PAD ANNULI",
        "   (BOTH PLANAR END LANDS), AND 4X CYLINDRICAL ODS OF THE PADS.",
    )
)
INSPECTION_NOTES = "\n".join(
    (
        "INSPECTION NOTES — 4X CORNER PAD OD/BORE:",
        "FIT LEAST-SQUARES CYLINDERS TO EACH EXPOSED OD ARC",
        "AND FULL BORE.",
        "USE 8 EQUALLY SPACED AXIAL SECTIONS OVER 47.00 AND",
        "8 EQUALLY SPACED ACCESSIBLE-ARC POINTS PER SECTION.",
        "AXIS OFFSET 0.05 MAX = GREATEST AXIS SEPARATION AT",
        "EITHER END PLANE.",
        "RADIAL WALL = POINT-TO-BORE-AXIS DISTANCE MINUS",
        "FITTED BORE RADIUS.",
        "MAX-MIN RADIAL WALL THICKNESS SHALL NOT EXCEED 0.10",
        "ACROSS ALL 64 OD POINTS. THIS CHECK IS ADDITIONAL TO",
        "NATIVE SIZE/POSITION CONTROLS.",
    )
)
TOP_VIEW_NOTE = "PLAN VIEW SCALE 1:2"
FRONT_VIEW_NOTE = "FRONT VIEW SCALE 1:4"
