#!/usr/bin/env python3
"""Adopt all six original-source corpora using independently decoded native proof.

Run from the repository root:
  python web/scripts/adopt-v39-source-observations.py

Both approved raw GLBs must be in web/.vite/model-source/<original-sha>.glb.
No CAD, browser, runtime generator, camera fit, or source video decoder is invoked.
Historical files are read-only. All six observations are prepared before one
transactional directory publication; do not run family producers concurrently.
Existing current family packets are retained. Current tracks are regenerated by
their owners after adoption; old source tracks contribute source facts, not fits.

The reviewed final source-only layout census is pinned independently of native
fits. Recorded exact-PTS corrections reconcile all six corpora; only the two
documented static-shot corrections extend over an interval. Unexplained layouts
refuse publication. Original operation events/measurements survive recursively,
with old native associations unavailable. Opacity remains explicitly chosen;
old fitted image warps are inactive, and every current stage remains unmeasured.
Recorded phase-point enrichment is normalized only through its sealed original
source map and independent reference measurements before exact-exposure union.
Pixel, role, method, uncertainty, image, and layout conflicts still fail closed;
this retained source evidence does not qualify current native playback.
"""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import math
import os
import re
import shutil
import tempfile
from pathlib import Path

_spec = importlib.util.spec_from_file_location("v39_adoption_common", Path(__file__).with_name("compact-source-common.py"))
common = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(common)
native = common._association

# These are original media observations, not recovered native state/camera data.
FRAME_SOURCE_FIELDS = {
    "timeSeconds", "decodedTimeSeconds", "decodedFrameIndex", "sourceFrameIndex", "nativeFrame",
    "shotId", "classification", "sourceMachineRequirement", "sourceImage", "landmarks", "unavailable",
    "retainedObservationTimeSeconds", "changeEvidence", "viewBoundaryStatus", "viewportCorrespondenceBlocker",
    "sourceObservationAuthority", "sourceObservationHistory", "sourceFeatureMeasurements", "sourceFeatureUnavailable",
    "sourceContourChecks", "sourceRodBodyMeasurements", "sourceRodEdgeObservation", "unresolvedSourceRodBodies",
}
VIEW_SOURCE_FIELDS = {
    "id", "classification", "rectSourcePixels", "rectUncertaintyPx", "presentation",
    "composite", "compositeEvidence", "compositeProvenance", "sourceCompositeEvidence", "blendEvidence",
    "rectEvidence", "evidence", "sourceViewportEvidence", "viewportEvidence", "sourceViewIds", "sourceViewMappingEvidence",
    "nativeLineChecks", "sourceContourChecks",
    "retiredNativePresentation",
}
SHOT_NATIVE_FIELDS = {"mechanicalState", "nativePose", "camera", "cameraEvidence", "cameraFit"}
SOURCE_MEASUREMENT_FIELDS = {"observedFeaturePixels", "unresolvedInputFields"}

# Frozen preceding/final source-layout ledgers at 7ec232aa26f517adce534d1882088608792048ab.
# The digest projects source identity, original model identity, shots and exact-PTS
# topology only. Camera/input/fit/GPU values, opacity and fitted image warps cannot
# authorize a correction. New unexplained source layouts require primary review.
RECORDED_SOURCE_LAYOUT_DIGESTS = {
    "NAsM30MAHLg": {
        "observations": "1f512de62050e7a7ce471e574fbb22c5579a0bfe5789acbd5d2e4593820e6410",
        "source-track": "9fa194998077378084a9e0ee5fbb19bedc104e9208b54ed1527ba037a4b5322a"},
    "8KmVDxkia_w": {
        "observations": "b825a09019b702051f1562572881a3b42e4099da901f5a33078b2e8d8f524612",
        "track": "f0099715eef5bf0ae0e7a56613186ab0923ddfc4bc8a1b7df3b3a1534cf9be16",
        "source-track": "91f2135f41d55f4d026c8d011b25d8b9a04e097a4dc3bda0bffcc8a2df13ba10"},
    "6dW6VYXp9HM": {
        "observations": "1e7d721ab8f357805ed48346d3752796670a94856bf25a73f1d38883138f00c0",
        "source-track": "392a48a2de712e8372fd0e84609624ddbba5e026f7e69d5ee7fbd6c9f1b0ca8f"},
    "jfH-NbsmvD4": {
        "observations": "43316b4c207010587717d488cbfb760c2428cc1f9262e016a4538d5478e31a60",
        "source-track": "3e9e172e58b45c6ff9d32344c7b1471216665e363f4a2682780484169809ed9f"},
    "XPQwKRt4Y2k": {
        "observations": "e7d049e5914c3180fb9923a63d5adf9ee91fae8749bab36d170e9af6bcdc9121",
        "track": "e7d049e5914c3180fb9923a63d5adf9ee91fae8749bab36d170e9af6bcdc9121",
        "source-track": "2245340ae8a1c6ec679b60e654bd64d4c2dcb34bc11e97ef3895a25ab5c4f9f4"},
    "4mBuyixt22U": {
        "observations": "aba9e22db13277677ce3c1b5812d5ef8147be7f38907424efb8a2a99f71e94d5",
        "source-track": "562a2f7f59f8a4447080f64f6379429ab4a8b2a9266247e2bcf0d01cd6c86106"},
}
CONSTANT_SOURCE_LAYOUT_CORRECTIONS = {
    ("6dW6VYXp9HM", "analysis-39"):
        "Final source-track evidence.notes records independently inspected original-MP4 endcard boxes at220s, with all eight views required throughout this endcard shot. Donor camera/input numbers are not source facts.",
    ("8KmVDxkia_w", "presenter-to-spin"):
        "Final source-track view.cameraInterpolationEvidence records source-inspected single-machine normalization over all native exposures623..637. Only one full-frame main source view is retained; continuous camera numbers remain chosen.",
}
OPERATION_SOURCE_FIELDS = {
    "id", "timeRangeSeconds", "targets", "sourceFeatureMeasurements", "sequence", "states",
    "pairedMeasurements", "viewRectsSourcePixels", "sourceTemplateCorrelation", "replayMovementEnvelope",
}
OPERATION_NATIVE_FIELDS = {
    "input", "mechanicalState", "partOverrides", "phases", "normalizationConflict",
    "partLocalMetres", "worldMetres", "partLocalLineMetres", "partWorldLineMetres", "worldLineMetres",
}
SOURCE_CLOCK_FIELDS = {"nativeFrame", "nativeFrameIndex", "nativeStartFrame", "nativeEndFrame", "nativeTimeSeconds"}
NATIVE_FIT_FIELDS = {"fit", "fitReport", "fitResiduals", "fitRmsPx", "fitMaxPx", "fitStatus", "fitReceipt", "fitEvidence"}


def is_native_operation_field(key):
    # "fixture" and "fixtureHeadPixel" are observed source fields, not fits;
    # native decoded-media frame clocks are likewise not native-CAD state.
    return (key in OPERATION_NATIVE_FIELDS or key == "partPath" or key in NATIVE_FIT_FIELDS
            or (key.startswith("native") and key not in SOURCE_CLOCK_FIELDS)
            or key.startswith(("camera", "GPU")) or "certificate" in key.lower())


def unknown_state():
    return {"status": "unobservable", "input": None,
            "evidence": "Original source observations retained; no complete current native state is independently measured. Current playback choices belong to explicit chosen-unobserved family packets."}


def source_views(frame):
    if "views" not in frame:
        return None
    output = []
    for view in frame["views"]:
        record = {key: copy.deepcopy(value) for key, value in view.items() if key in VIEW_SOURCE_FIELDS}
        record.update(camera=None, mechanicalState=unknown_state())
        retired = [key for key in ("imagePlaneWarp", "resolvedImagePlaneWarp") if key in view]
        if retired:
            record["retiredNativePresentation"] = {
                "status": "historical-not-current", "model": copy.deepcopy(native.HISTORICAL_SOURCE),
                "fields": retired, "reason": "Fitted/chosen render-to-source warps are not independent source media observations; immutable originals retain their numeric candidates."}
        if (record.get("composite") or {}).get("mode") == "crossfade":
            record["compositeProvenance"] = {
                "kind": "chosen-unmeasured", "evidence": "Original composite topology remains a source obligation. Retained numeric opacity is an unmeasured presentation candidate, not source alpha or current native/GPU qualification."}
        output.append(record)
    return output


def source_frame(frame):
    result = {key: copy.deepcopy(value) for key, value in frame.items() if key in FRAME_SOURCE_FIELDS}
    result.setdefault("landmarks", [])
    result.setdefault("unavailable", [])
    views = source_views(frame)
    if views is not None:
        result["views"] = views
    measured = frame.get("sourceMeasurements")
    if isinstance(measured, dict):
        result["sourceMeasurements"] = {key: copy.deepcopy(value) for key, value in measured.items()
                                        if key in SOURCE_MEASUREMENT_FIELDS}
    result["camera"] = None
    result["mechanicalState"] = unknown_state()
    return result


def exposure_key(frame, source):
    image = frame.get("sourceImage")
    pts = frame.get("decodedTimeSeconds")
    if not isinstance(image, dict) or type(pts) not in (int, float) or not math.isfinite(pts):
        return None
    pixel_key = {"bgr8": "sha256Bgr8", "gray8": "sha256Gray8"}.get(image.get("pixelFormat"))
    if (not pixel_key or any(not isinstance(image.get(key), str)
                            or not re.fullmatch(r"[0-9a-f]{64}", image[key]) for key in ("sourceSha256", pixel_key))
            or type(image.get("frameIndex")) is not int or image["frameIndex"] < 0
            or any(type(image.get(key)) is not int or image[key] <= 0 for key in ("width", "height"))
            or any(key in frame and (type(frame[key]) is not int or frame[key] != image["frameIndex"])
                   for key in ("decodedFrameIndex", "sourceFrameIndex", "nativeFrame"))):
        return None
    if (image["sourceSha256"] != source["sha256"]
            or any(image[key] != source[key] for key in ("width", "height"))):
        return None
    return (frame["shotId"], frame["decodedTimeSeconds"], image.get("frameIndex"),
            image.get("sourceSha256"), image.get("pixelFormat"), image.get(pixel_key), image.get("width"), image.get("height"))


def layout_key(frame):
    views = frame.get("views")
    if views is None:
        return None
    return native.canonical(source_layout(views))


def union_declarations(first, second):
    seen = {native.canonical(item) for item in first}
    for item in second:
        key = native.canonical(item)
        if key not in seen:
            first.append(copy.deepcopy(item))
            seen.add(key)



def source_layout(views):
    """Only source view identity/rectangle/presentation and composite topology."""
    layout = []
    for view in views:
        record = {key: copy.deepcopy(view[key]) for key in
                  ("id", "rectSourcePixels", "presentation", "sourceViewIds", "sourceViewMappingEvidence")
                  if key in view}
        record.setdefault("presentation", "native")
        if view.get("composite"):
            record["composite"] = {key: copy.deepcopy(view["composite"][key])
                                   for key in ("mode", "groupId", "imageLayerId") if key in view["composite"]}
        layout.append(record)
    return layout


def source_layout_census_digest(document):
    rows = [{"shotId": frame["shotId"], "decodedTimeSeconds": frame["decodedTimeSeconds"],
             "classification": frame["classification"], "sourceMachineRequirement": frame.get("sourceMachineRequirement"),
             "layout": source_layout(common.source_views(frame, document))} for frame in document["frames"]]
    rows.sort(key=lambda row: (row["shotId"], row["decodedTimeSeconds"], native.canonical(row["layout"])))
    census = {"source": {key: document["source"][key] for key in
                        ("videoId", "sha256", "width", "height", "fps", "durationSeconds")},
              "model": {key: document["model"][key] for key in native.HISTORICAL_SOURCE},
              "shots": [{key: shot[key] for key in
                         ("id", "startSeconds", "endSeconds", "classification", "hasCorrespondingMachine")
                         if key in shot} for shot in document["shots"]], "frames": rows}
    return hashlib.sha256(native.canonical(census).encode("utf-8")).hexdigest()


def validate_source_layout(frame, source):
    ids = set()
    for view in frame["views"]:
        ident, rect = view.get("id"), view.get("rectSourcePixels")
        if (not isinstance(ident, str) or not ident or ident in ids
                or not isinstance(rect, list) or len(rect) != 4
                or any(type(value) not in (int, float) or not math.isfinite(value) for value in rect)
                or rect[0] < 0 or rect[1] < 0 or rect[2] <= 0 or rect[3] <= 0
                or rect[0] + rect[2] > source["width"] + 1e-7
                or rect[1] + rect[3] > source["height"] + 1e-7
                or view.get("presentation", "native") not in ("native", "horizontal-mirror")):
            raise ValueError(f"Unknown/invalid source view layout at {frame['shotId']}/{frame['decodedTimeSeconds']}")
        ids.add(ident)
        composite = view.get("composite")
        if composite and (composite.get("mode") not in ("opaque", "crossfade")
                or (composite["mode"] == "crossfade" and (
                    any(not isinstance(composite.get(key), str) or not composite[key] for key in ("groupId", "imageLayerId"))
                    or type(composite.get("opacity")) not in (int, float)
                    or not math.isfinite(composite["opacity"]) or not 0 <= composite["opacity"] <= 1))):
            raise ValueError(f"Unknown/invalid source composite layout at {frame['shotId']}/{frame['decodedTimeSeconds']}")


def replace_source_layout(frame, chosen, authority):
    """Reconcile layout only; never transplant an image, CHECK, camera or state."""
    old_views = {view["id"]: view for view in frame["views"]}
    old_layout = source_layout(frame["views"])
    changed = old_layout != source_layout(chosen["views"])
    compatible = {view["id"] for view in chosen["views"] if view["id"] in old_views
                  and source_layout([view]) == source_layout([old_views[view["id"]]])}
    if changed:
        lost_points = []
        points = []
        for point in frame["landmarks"]:
            ident = point.get("viewId", "main")
            if ident in compatible:
                points.append(point)
            else:
                lost_points.append(copy.deepcopy(point))
                union_declarations(frame["unavailable"], [{
                    "anchorId": point["anchorId"], "viewId": ident, "originalViewId": ident,
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "sourceImage": copy.deepcopy(frame.get("sourceImage")),
                    "decodedTimeSeconds": frame["decodedTimeSeconds"], "required": True,
                    "status": "source-unavailable",
                    "reason": "Original source landmark belongs to a superseded incompatible layout; no new-view alias or pixel measurement is inferred."}])
        frame["landmarks"] = points
        for ident, view in old_views.items():
            if ident in compatible:
                continue
            for field in ("nativeLineChecks", "sourceContourChecks"):
                for item in view.get(field, []):
                    union_declarations(frame["unavailable"], [{
                        "contourId": item.get("id", item.get("contourId")), "viewId": ident, "originalViewId": ident,
                        "role": item.get("role"), "sourceObservation": source_operation_value(item),
                        "originalPartPath": item.get("partPath"), "required": True, "status": "source-unavailable",
                        "sourceImage": copy.deepcopy(frame.get("sourceImage")), "decodedTimeSeconds": frame["decodedTimeSeconds"],
                        "reason": "Original source contour belongs to a superseded incompatible view; fresh current correspondence is required."}])
        history = frame.setdefault("sourceObservationHistory", [])
        union_declarations(history, [{"kind": "superseded-source-layout", "layout": old_layout,
                                      "incompatibleLandmarks": lost_points}])
        frame["sourceObservationAuthority"] = copy.deepcopy(authority)
    output = []
    for chosen_view in chosen["views"]:
        # Only presentation/layout candidates can be shared by a recorded
        # exact-PTS/static-shot correction. Source measurements stay on their
        # own original exposure, including when the same PTS has unequal hashes.
        view = {key: copy.deepcopy(value) for key, value in chosen_view.items()
                if key not in ("nativeLineChecks", "sourceContourChecks")}
        if view["id"] in compatible:
            for field in ("nativeLineChecks", "sourceContourChecks"):
                if field in old_views[view["id"]]:
                    view[field] = copy.deepcopy(old_views[view["id"]][field])
        output.append(view)
    frame["views"] = output


def normalize_recorded_phase_points(prepared, documents):
    """Reuse the sealed source-only proof before any strict alias comparison."""
    declarations = {}
    for document in documents:
        for frame in document["frames"]:
            for point in frame.get("landmarks", []):
                tracking = point.get("trackingEvidence") or {}
                if tracking.get("kind") != "retained-source-phase-patch-reacquisition":
                    continue
                declaration = tracking.get("phaseMap")
                if not isinstance(declaration, dict) or not declaration.get("path") or not declaration.get("sha256"):
                    raise ValueError("Retained source phase evidence has no sealed original phase-map declaration")
                declarations[native.canonical(declaration)] = declaration
    if not declarations:
        return None
    if len(declarations) != 1 or not documents[0].get("sourceCameraRigs"):
        raise ValueError("Conflicting/missing original source phase-map/reference authority")
    declaration = next(iter(declarations.values()))
    source = {"frames": [frame for records in prepared for frame in records],
              "sourceCameraRigs": documents[0]["sourceCameraRigs"]}
    return common.retain_phase_point_provenance(source, {"independentSourcePhaseMap": declaration})


def reconcile_source_documents(documents, lineage):
    original = documents[0]
    shots = [{key: copy.deepcopy(value) for key, value in shot.items() if key not in SHOT_NATIVE_FIELDS}
             for shot in original["shots"]]
    shot_by_id = {shot["id"]: shot for shot in shots}
    groups, prepared = {}, []
    approved, authority = {}, None
    for document, origin in zip(documents, lineage):
        suffix = origin["path"].removesuffix(".json").rsplit(".", 1)[1]
        digest = source_layout_census_digest(document)
        if digest != RECORDED_SOURCE_LAYOUT_DIGESTS.get(original["source"]["videoId"], {}).get(suffix):
            raise ValueError("Recorded source-layout census digest is unknown; no conflicting earlier/later layout authority inferred")
        if suffix == "source-track" and document.get("kind") != "compact-source-track":
            raise ValueError("Designated source-track must declare its approved compact source-layout census")
        if any(shot["id"] not in shot_by_id for shot in document["shots"]):
            raise ValueError("Supplemental source introduces an unexplained shot identity")
        for shot in document["shots"]:
            if shot.get("hasCorrespondingMachine") is True:
                shot_by_id[shot["id"]]["hasCorrespondingMachine"] = True
        records = []
        for original_frame in document["frames"]:
            frame = source_frame(original_frame)
            if "views" not in frame:
                frame["views"] = source_views({"views": common.source_views(original_frame, document)})
            validate_source_layout(frame, original["source"])
            if type(frame.get("decodedTimeSeconds")) not in (int, float) or not math.isfinite(frame["decodedTimeSeconds"]):
                raise ValueError("Historical source layout has no actual decoded PTS")
            if frame["shotId"] not in shot_by_id:
                raise ValueError("Historical source frame has an unexplained shot identity")
            key = (frame["shotId"], frame["decodedTimeSeconds"])
            groups.setdefault(key, []).append(frame)
            records.append(frame)
        prepared.append(records)
        if suffix == "source-track":
            if authority is not None:
                raise ValueError("Competing final source-layout authorities")
            authority = {"kind": "recorded-source-layout-reconciliation", "historicalInput": copy.deepcopy(origin),
                         "sourceLayoutCensusSha256": digest,
                         "scope": "Source layout requirements only; no camera/input/warp/native/GPU certificate adoption"}
            for frame in records:
                key = (frame["shotId"], frame["decodedTimeSeconds"])
                if key in approved and layout_key(approved[key]) != layout_key(frame):
                    raise ValueError("Recorded source-layout census has conflicting equal-PTS layouts")
                approved[key] = frame
    if authority is None:
        raise ValueError("One designated approved final source-layout census is required")
    phase_provenance = normalize_recorded_phase_points(prepared, documents)
    constants = {}
    for (video_id, shot_id), evidence in CONSTANT_SOURCE_LAYOUT_CORRECTIONS.items():
        if video_id != original["source"]["videoId"] or authority is None or shot_id not in shot_by_id:
            continue
        candidates = [frame for (ident, _), frame in approved.items() if ident == shot_id]
        if not candidates or len({layout_key(frame) for frame in candidates}) != 1:
            raise ValueError("Documented constant-shot source correction is missing/contradictory")
        constants[shot_id] = (candidates[0], {**authority, "constantShotEvidence": evidence})
    for key, aliases in groups.items():
        chosen, declaration = approved.get(key), authority
        shot = shot_by_id[key[0]]
        if key[0] in constants and shot["startSeconds"] <= key[1] < shot["endSeconds"]:
            chosen, declaration = constants[key[0]]
        if chosen is not None:
            for frame in aliases:
                replace_source_layout(frame, chosen, declaration)
        elif len({layout_key(frame) for frame in aliases}) != 1:
            raise ValueError(f"Unexplained conflicting source layout at {key}; equal-PTS ordering is not authority")
        shot = shot_by_id[key[0]]
        if (shot.get("hasCorrespondingMachine") is True
                or any(frame.get("sourceMachineRequirement") == "required" or frame["classification"] == "machine" for frame in aliases)):
            for frame in aliases:
                frame["sourceMachineRequirement"] = "required"
    frames = prepared[0]
    for supplemental in prepared[1:]:
        retain_supplemental_frames(frames, supplemental, original["source"])
    return frames, shots, authority, phase_provenance


def retain_exposure_obligations(frames):
    """Selection among equal-PTS rows cannot waive a required machine or loss."""
    groups = {}
    for frame in frames:
        groups.setdefault((frame["shotId"], frame["decodedTimeSeconds"]), []).append(frame)
    for aliases in groups.values():
        losses = []
        for frame in aliases:
            union_declarations(losses, frame["unavailable"])
        required = any(frame.get("sourceMachineRequirement") == "required" for frame in aliases)
        for frame in aliases:
            union_declarations(frame["unavailable"], losses)
            if required:
                frame["sourceMachineRequirement"] = "required"


def source_operation_value(value):
    if isinstance(value, list):
        return [source_operation_value(item) for item in value]
    if not isinstance(value, dict):
        return copy.deepcopy(value)
    result, retired = {}, []
    path = value.get("partPath")
    for key, item in value.items():
        if is_native_operation_field(key):
            retired.append(key)
        elif key == "evidence":
            result["historicalObservationEvidence"] = {
                "model": copy.deepcopy(native.HISTORICAL_SOURCE), "text": copy.deepcopy(item),
                "scope": "Original mixed source/native narrative; any historical native support is not current qualification"}
        else:
            result[key] = source_operation_value(item)
    if retired:
        result["retiredNativeFields"] = retired
        result["nativeAssociation"] = {"status": "unavailable",
            "reason": "Observed source operation facts survive; historical operation pose/feature associations and qualification do not transfer to the current native model"}
    if path:
        result["originalPartPath"] = copy.deepcopy(path)
    if value.get("nativePartPaths"):
        result["originalNativePartPaths"] = copy.deepcopy(value["nativePartPaths"])
    return result


def operation_observation_identity(value):
    if isinstance(value, list):
        return [operation_observation_identity(item) for item in value]
    if isinstance(value, dict):
        return {key: operation_observation_identity(item) for key, item in value.items()
                if key not in ("retiredNativeFields", "nativeAssociation", "originalPartPath",
                               "originalNativePartPaths", "historicalObservationEvidence", "sourceObservationHistory")}
    return value


def source_operations(documents):
    by_id = {}
    for document in documents:
        for original in document.get("operations", []):
            # Retire known native top-level fields without dropping their
            # nested source event/measurement siblings.
            unknown = [key for key in original if key not in OPERATION_SOURCE_FIELDS
                and key not in SOURCE_CLOCK_FIELDS and key != "evidence" and not is_native_operation_field(key)]
            if unknown:
                raise ValueError(f"Unexplained source operation fields cannot be dropped: {unknown}")
            record = source_operation_value(original)
            prior = by_id.get(record["id"])
            if prior is not None:
                if operation_observation_identity(prior) != operation_observation_identity(record):
                    raise ValueError("Conflicting original source operation facts; no later-row selection")
                if prior != record:
                    union_declarations(prior.setdefault("sourceObservationHistory", []),
                        [{"kind": "historical-operation-declaration", "sourceOperation": record}])
            else:
                by_id[record["id"]] = record
    return list(by_id.values())


def operation_change_times(operations):
    times = set()
    for operation in operations:
        times.update(operation.get("timeRangeSeconds", []))
        for field in ("sequence", "states"):
            for step in operation.get(field, []):
                times.update(step.get("seconds", []))
        for field in ("targets", "sourceFeatureMeasurements", "pairedMeasurements"):
            times.update(point["timeSeconds"] for point in operation.get(field, []) if "timeSeconds" in point)
    return times


def merge_source_measurements(existing, supplemental):
    for field in ("sourceFeatureMeasurements", "sourceFeatureUnavailable", "sourceContourChecks",
                  "sourceRodBodyMeasurements", "sourceRodEdgeObservation", "unresolvedSourceRodBodies",
                  "sourceObservationHistory", "sourceMeasurements"):
        value = supplemental.get(field)
        if value is None:
            continue
        if field not in existing:
            existing[field] = copy.deepcopy(value)
        elif isinstance(existing[field], list) and isinstance(value, list):
            union_declarations(existing[field], value)
        elif existing[field] != value:
            union_declarations(existing["unavailable"], [{
                "field": field, "sourceObservation": copy.deepcopy(value), "required": True,
                "reason": "Unequal original source declarations on one exact exposure; alternate fact retained without selecting a measurement"}])
    by_id = {view["id"]: view for view in existing.get("views", [])}
    for view in supplemental.get("views", []):
        prior = by_id.get(view["id"])
        if prior is None:
            continue
        for field in ("nativeLineChecks", "sourceContourChecks"):
            if field in view:
                union_declarations(prior.setdefault(field, []), view[field])

def retain_supplemental_frames(frames, supplements, source):
    """Retain explicit source rows only; never nearest-frame, PTS, pixel or camera borrowing."""
    identity_rows, layouts_by_pts = {}, {}
    for frame in frames:
        layout = layout_key(frame)
        identity_rows.setdefault((frame["timeSeconds"], exposure_key(frame, source), layout), []).append(frame)
        if layout is not None:
            layouts_by_pts.setdefault((frame["shotId"], frame["decodedTimeSeconds"]), set()).add(layout)
    for original in supplements:
        if original.get("decodedTimeSeconds") is None:
            raise ValueError("Historical supplemental source record has no actual decoded PTS")
        frame = source_frame(original)
        layout = layout_key(frame)
        pts_key = (frame["shotId"], frame["decodedTimeSeconds"])
        known_layouts = layouts_by_pts.setdefault(pts_key, set())
        if layout is not None:
            if known_layouts and known_layouts != {layout}:
                raise ValueError("Unexplained conflicting equal-PTS source layout; reconcile recorded source authority before union")
            known_layouts.add(layout)
        exposure = exposure_key(frame, source)
        key = (frame["timeSeconds"], exposure, layout)
        matches = identity_rows.get(key, [])
        # Missing image identity is not an authority for exposure union.
        if exposure is not None and len(matches) == 1:
            existing = matches[0]
            known = {(p.get("viewId", "main"), p["anchorId"]): p for p in existing["landmarks"]}
            for point in frame["landmarks"]:
                prior = known.get((point.get("viewId", "main"), point["anchorId"]))
                if prior is not None and prior != point:
                    # Different declaration remains an original required loss,
                    # not a conveniently selected new measurement.
                    existing["unavailable"].append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                        "role": point.get("role"), "sourcePixels": point.get("pixel"), "required": True,
                        "reason": "Conflicting original declarations on the same exact exposure/layout; no measurement is selected"})
                elif prior is None:
                    existing["landmarks"].append(copy.deepcopy(point))
            union_declarations(existing["unavailable"], frame["unavailable"])
            merge_source_measurements(existing, frame)
            if frame.get("sourceMachineRequirement") == "required":
                existing["sourceMachineRequirement"] = "required"
        else:
            frames.append(frame)
            identity_rows.setdefault(key, []).append(frame)
    frames.sort(key=lambda frame: (frame["timeSeconds"], frame["decodedTimeSeconds"], layout_key(frame) or ""))


def associate_source_body_facts(frames, association):
    """Retain source facts; one full raw-native body proof per exact authored path."""
    body_proofs = {}
    proof_digests = {}
    for frame in frames:
        contexts = [(frame, "main"), *[(view, view["id"]) for view in frame.get("views", [])]]
        for context, view_id in contexts:
            for field in ("nativeLineChecks", "sourceContourChecks", "sourceRodBodyMeasurements", "unresolvedSourceRodBodies"):
                for item in context.get(field, []):
                    path = item.get("partPath")
                    if not path:
                        continue
                    if path not in body_proofs:
                        body = association.associate_native_part(path)
                        serialized = native.canonical(body)
                        body_proofs[path] = {**body, "serializedProof": serialized}
                        proof_digests[path] = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
                    body = body_proofs[path]
                    proof = {"status": body["status"], "reason": body["reason"],
                             "proofRef": path, "proofSha256": proof_digests[path]}
                    item["nativeAssociation"] = proof
                    item["originalPartPath"] = path
                    # Historical residual/native-bias summaries are not current qualification.
                    for key in list(item):
                        if key.startswith("nativeCandidate"):
                            del item[key]
                    evidence = item.get("measurementEvidence")
                    if isinstance(evidence, dict):
                        old_bias = {key: evidence.pop(key) for key in ("axisPerspectiveBiasBoundPx", "axisPerspectiveEvidence") if key in evidence}
                        if old_bias:
                            item["historicalNativeEvidence"] = {"model": native.HISTORICAL_SOURCE, **old_bias}
                    world_line = item.get("partWorldLineMetres", item.get("worldLineMetres"))
                    if proof["status"] == "mapped" and world_line is not None:
                        if item.get("partLocalLineMetres") is not None or not isinstance(world_line, list) or not all(native.finite_vector(point, 3) for point in world_line):
                            proof["status"], proof["reason"] = "unavailable", "Original native line has ambiguous local/world coordinate authority"
                        else:
                            item["partLocalLineMetres"] = [native.localize_old_world(body["proof"]["historicalWorldMatrix"], point) for point in world_line]
                            item.pop("partWorldLineMetres", None)
                            item.pop("worldLineMetres", None)
                    if proof["status"] == "unavailable":
                        item.pop("partPath", None)
                        for key in ("partLocalLineMetres", "partWorldLineMetres", "worldLineMetres"):
                            item.pop(key, None)
                        frame["unavailable"].append({
                            "contourId": item.get("id", item.get("contourId")), "viewId": view_id,
                            "role": item.get("role"), "originalPartPath": path, "status": "unmeasured-native",
                            "required": True, "reason": proof["reason"]})
    return body_proofs


def retain_association_losses(frames, anchors):
    associations = {anchor["id"]: anchor["nativeAssociation"] for anchor in anchors}
    for frame in frames:
        losses = []
        view_ids = {view["id"] for view in frame.get("views", [])}
        if frame.get("sourceMachineRequirement") == "required" and not view_ids:
            losses.append({"viewId": None, "originalViewId": None, "required": True, "status": "source-unavailable",
                           "reason": "Original required machine has no identified source view/layout; an empty layout is not a HOLD exemption"})
        for point in frame.get("landmarks", []):
            view_id = point.get("viewId", "main")
            if view_id not in view_ids:
                losses.append({"anchorId": point["anchorId"], "viewId": view_id, "originalViewId": view_id,
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "required": True, "status": "source-unavailable",
                    "reason": "Original source landmark view/layout is unidentified; no main/inset alias is inferred"})
        for point in frame.get("landmarks", []):
            association = associations.get(point["anchorId"])
            if association is None or association["status"] == "unavailable":
                losses.append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "status": "unmeasured-native", "required": True,
                    "reason": association["reason"] if association else "Original source landmark has no uniquely identified native anchor"})
        # Source-only unidentified features/losses are requirements even when
        # they were not admitted as measured FIT/CHECK anchors.
        for point in frame.get("landmarks", []):
            if point.get("status") != "observed" or point.get("pixel") is None:
                losses.append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "required": True, "reason": "Original required source feature is unresolved/unobserved; no measurement inferred"})
        for item in frame.get("sourceFeatureUnavailable", []):
            losses.append({**copy.deepcopy(item), "required": True} if isinstance(item, dict)
                          else {"reason": copy.deepcopy(item), "required": True})
        union_declarations(frame["unavailable"], losses)


def retain_declared_tracking_losses(frames, documents):
    """Top-level source-only loss events must reach the required frame ledger too."""
    by_exposure = {}
    for frame in frames:
        by_exposure.setdefault((frame["shotId"], frame["decodedTimeSeconds"]), []).append(frame)
    for document in documents:
        for loss in document.get("trackingLosses", []):
            matches = by_exposure.get((loss.get("shotId"), loss.get("decodedTimeSeconds")), [])
            if not matches:
                raise ValueError("Original tracking loss has no retained actual source exposure; cannot drop or invent its PTS")
            for frame in matches:
                declaration = {**copy.deepcopy(loss), "viewId": loss.get("viewId"),
                    "originalViewId": loss.get("viewId"), "role": loss.get("role"),
                    "sourcePixels": copy.deepcopy(loss.get("pixel")), "status": "source-unavailable", "required": True}
                union_declarations(frame["unavailable"], [declaration])

def adopt_video(video_id, association=None, historical_root=None):
    root = historical_root or common.HISTORICAL_CONTENT
    association = association or native.native_association()
    documents, lineage = [], []
    for suffix in ("observations", "track", "source-track"):
        path = root / f"{video_id}.{suffix}.json"
        if suffix == "track" and not path.exists():
            continue
        raw = path.read_bytes()
        document = json.loads(raw)
        if (document.get("source", {}).get("videoId") != video_id
                or any(document.get("model", {}).get(key) != value for key, value in native.HISTORICAL_SOURCE.items())):
            raise ValueError(f"Historical corpus does not target its original source/model: {path}")
        if documents and document["source"]["sha256"] != documents[0]["source"]["sha256"]:
            raise ValueError("Historical supplemental source differs from original footage")
        documents.append(document)
        lineage.append({"path": f"content/{path.name}", "sha256": native.hashlib.sha256(raw).hexdigest(),
                        "model": copy.deepcopy(document["model"]), "scope": "Immutable historical input; native/camera/GPU certificates not current qualification"})
    original = documents[0]
    anchor_catalog = {}
    conflicts = set()
    for document in documents:
        for anchor in document.get("anchors", []):
            prior = anchor_catalog.get(anchor["id"])
            if prior is None:
                anchor_catalog[anchor["id"]] = anchor
            elif any(prior.get(key) != anchor.get(key) for key in ("partPath", "partLocalMetres", "worldMetres")):
                conflicts.add(anchor["id"])
    rows = []
    for anchor_id, anchor in anchor_catalog.items():
        row = association.associate_native_anchor(anchor)
        if anchor_id in conflicts:
            reason = "Historical catalogs disagree on native feature coordinates/path; fresh primary mapping required"
            row = {"status": "unavailable", "reason": reason, "proof": row["proof"],
                   "anchor": {key: copy.deepcopy(anchor[key]) for key in ("id", "kind", "description") if key in anchor}}
            row["anchor"]["nativeAssociation"] = {"status": "unavailable", "reason": reason, "proof": row["proof"]}
        rows.append(row)
    frames, shots, layout_authority, phase_provenance = reconcile_source_documents(documents, lineage)
    operations = source_operations(documents)
    body_proofs = associate_source_body_facts(frames, association)
    anchors = [row["anchor"] for row in rows]
    retain_association_losses(frames, anchors)
    retain_declared_tracking_losses(frames, documents)
    retain_exposure_obligations(frames)
    compact_keys = {frame["timeSeconds"] for document in documents
                    if document.get("kind") == "compact-source-track" for frame in document["frames"]}
    for document in documents:
        compact_keys.update(document.get("compactChangeTimesSeconds", []))
        compact_keys.update(document.get("coverage", {}).get("changeTimesSeconds", []))
    compact_keys.update(operation_change_times(operations))
    coverage = {key: copy.deepcopy(value) for key, value in original.get("coverage", {}).items()
                if key in ("requiredEveryIntegerSecond", "requiredEveryChange", "requiredEveryNativeFrame", "changeTimesSeconds")}
    coverage["changeTimesSeconds"] = sorted({time for document in documents
        for time in document.get("coverage", {}).get("changeTimesSeconds", [])})
    coverage.update({"status": "blocked", "requiredEveryIntegerSecond": True,
        "blockers": ["Current raw-native associations do not qualify original source-first-surface, complete inputs, camera fits, or actual GPU matching.",
                     "All six 50/20/10/5 source matching stages remain unmeasured.",
                     *[f'{row["anchor"].get("id")}: {row["reason"]}' for row in rows if row["status"] == "unavailable"]]})
    result = {"schemaVersion": original["schemaVersion"], "source": copy.deepcopy(original["source"]),
              "model": common.current_model_identity(), "anchors": anchors,
              "shots": shots, "frames": frames, "coverage": coverage,
              "compactChangeTimesSeconds": sorted(compact_keys),
              "nativeBodyAssociations": body_proofs,
              "stages": {str(stage): {"status": "unmeasured"} for stage in (50, 20, 10, 5)},
              "sourceMeasurements": {"status": "partial", "blockers": coverage["blockers"]},
              "nativeAdoption": {"status": "associated-with-required-losses", "sourceAcceptance": False,
                    "GPUAcceptance": False, "mappedAnchorCount": sum(row["status"] == "mapped" for row in rows),
                    "unavailableAnchorCount": sum(row["status"] == "unavailable" for row in rows),
                    "historicalInputs": lineage,
                    "sourceLayoutReconciliation": layout_authority,
                    "sourcePhasePointProvenance": phase_provenance,
                    "interpretation": "Exact original-source media facts plus fresh original-GLB native association. No old source certificate was relabelled."}}
    if original.get("nativeGeometryAssumptions"):
        result["nativeGeometryAssumptions"] = copy.deepcopy(original["nativeGeometryAssumptions"])
    if original.get("sourceCameraRigs"):
        result["sourceCameraRigs"] = [
            {key: copy.deepcopy(value) for key, value in rig.items()
             if key in ("kind", "id", "phaseCount", "phaseImages", "measurements", "independentLoopEvidence", "rejectedMeasurements")}
            for rig in original["sourceCameraRigs"]]
    if original.get("trackingLosses"):
        result["trackingLosses"] = copy.deepcopy(original["trackingLosses"])
    if operations:
        result["operations"] = operations
    return result


def _publish_six_records(prepared, suffix, current_root=None):
    """All-or-nothing current directory transaction; preserve other current packets."""
    target = current_root or common.CURRENT_CONTENT
    if set(prepared) != set(common.VIDEO_IDS):
        raise ValueError("Only the complete six-video current corpus transaction may publish")
    target.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".v39-{suffix}-", dir=target.parent))
    backup = staging / "previous"
    staged = staging / "current"
    had_target = target.exists()
    published = False
    try:
        if had_target:
            shutil.copytree(target, staged)
        else:
            staged.mkdir()
        for video_id, data in prepared.items():
            if data.get("model") != common.current_model_identity() or data.get("source", {}).get("videoId") != video_id:
                raise ValueError("Prepared current record model/video identity mismatch")
            (staged / f"{video_id}.{suffix}.json").write_text(json.dumps(data, separators=(",", ":"), allow_nan=False) + "\n")
        if had_target:
            os.replace(target, backup)
        try:
            os.replace(staged, target)
            published = True
        except BaseException:
            if had_target:
                os.replace(backup, target)
            raise
    finally:
        if published or not backup.exists():
            shutil.rmtree(staging)


def publish_observations(prepared, current_root=None):
    return _publish_six_records(prepared, "observations", current_root)


def publish_tracks(prepared, current_root=None):
    for track in prepared.values():
        if (track.get("kind") != "compact-source-track"
                or track.get("stages") != {str(stage): {"status": "unmeasured"} for stage in (50, 20, 10, 5)}):
            raise ValueError("Current generation must publish compact tracks with all four stages unmeasured")
        common.prepare_track(track)
    return _publish_six_records(prepared, "source-track", current_root)


def main():
    association = native.native_association()
    prepared = {video_id: adopt_video(video_id, association) for video_id in common.VIDEO_IDS}
    publish_observations(prepared)
    print(json.dumps({"contentRoot": "web/content/v39", "videos": [
        {"videoId": video_id, "frames": len(data["frames"]),
         "mappedAnchors": data["nativeAdoption"]["mappedAnchorCount"],
         "unavailableAnchors": data["nativeAdoption"]["unavailableAnchorCount"],
         "sourceAcceptance": False, "GPUAcceptance": False} for video_id, data in prepared.items()]}))


if __name__ == "__main__":
    main()
