#!/usr/bin/env python3
"""Adopt all six original-source corpora using independently decoded native proof.

Run from the repository root:
  python web/scripts/adopt-v39-source-observations.py

Both approved raw GLBs must be in web/.vite/model-source/<original-sha>.glb.
No CAD, browser, runtime generator, camera fit, or source video decoder is invoked.
Historical files are read-only. All six observations are prepared before one
transactional directory publication; do not run family producers concurrently.
Existing current family packets are retained. Current tracks are regenerated by
their owners after adoption; old source tracks contribute source facts, not fits.
"""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import os
import shutil
import tempfile
from pathlib import Path

_spec = importlib.util.spec_from_file_location("v39_adoption_common", Path(__file__).with_name("compact-source-common.py"))
common = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(common)
native = common._association

# These are original media observations, not recovered native state/camera data.
FRAME_SOURCE_FIELDS = {
    "timeSeconds", "decodedTimeSeconds", "decodedFrameIndex", "sourceFrameIndex", "nativeFrame",
    "shotId", "classification", "sourceMachineRequirement", "sourceImage", "landmarks", "unavailable",
    "retainedObservationTimeSeconds", "changeEvidence", "viewBoundaryStatus", "viewportCorrespondenceBlocker",
    "sourceObservationAuthority", "sourceObservationHistory", "sourceFeatureMeasurements", "sourceFeatureUnavailable",
    "sourceContourChecks", "sourceRodBodyMeasurements", "sourceRodEdgeObservation", "unresolvedSourceRodBodies",
}
VIEW_SOURCE_FIELDS = {
    "id", "classification", "rectSourcePixels", "rectUncertaintyPx", "presentation", "imagePlaneWarp",
    "resolvedImagePlaneWarp", "composite", "compositeEvidence", "sourceCompositeEvidence", "blendEvidence",
    "rectEvidence", "evidence", "sourceViewportEvidence", "viewportEvidence", "sourceViewIds", "sourceViewMappingEvidence",
    "nativeLineChecks", "sourceContourChecks",
}
SHOT_NATIVE_FIELDS = {"mechanicalState", "nativePose", "camera", "cameraEvidence", "cameraFit"}
SOURCE_MEASUREMENT_FIELDS = {"observedFeaturePixels", "unresolvedInputFields"}


def unknown_state():
    return {"status": "unobservable", "input": None,
            "evidence": "Original source observations retained; no complete current native state is independently measured. Current playback choices belong to explicit chosen-unobserved family packets."}


def source_views(frame):
    if "views" not in frame:
        return None
    return [{**{key: copy.deepcopy(value) for key, value in view.items() if key in VIEW_SOURCE_FIELDS},
             "camera": None, "mechanicalState": unknown_state()}
            for view in frame["views"]]


def source_frame(frame):
    result = {key: copy.deepcopy(value) for key, value in frame.items() if key in FRAME_SOURCE_FIELDS}
    result.setdefault("landmarks", [])
    result.setdefault("unavailable", [])
    views = source_views(frame)
    if views is not None:
        result["views"] = views
    measured = frame.get("sourceMeasurements")
    if isinstance(measured, dict):
        result["sourceMeasurements"] = {key: copy.deepcopy(value) for key, value in measured.items()
                                        if key in SOURCE_MEASUREMENT_FIELDS}
    result["camera"] = None
    result["mechanicalState"] = unknown_state()
    return result


def exposure_key(frame):
    image = frame.get("sourceImage")
    if not isinstance(image, dict) or not isinstance(frame.get("decodedTimeSeconds"), (int, float)):
        return None
    pixel_key = {"bgr8": "sha256Bgr8", "gray8": "sha256Gray8"}.get(image.get("pixelFormat"))
    if not pixel_key or not image.get(pixel_key):
        return None
    return (frame["shotId"], frame["decodedTimeSeconds"], image.get("frameIndex"),
            image.get("sourceSha256"), image.get("pixelFormat"), image.get(pixel_key), image.get("width"), image.get("height"))


def layout_key(frame):
    views = frame.get("views")
    if views is None:
        return None
    return native.canonical([{key: view.get(key) for key in ("id", "rectSourcePixels", "presentation", "composite",
                                 "imagePlaneWarp", "resolvedImagePlaneWarp", "sourceViewIds", "sourceViewMappingEvidence")}
                             for view in views])


def union_declarations(first, second):
    seen = {native.canonical(item) for item in first}
    for item in second:
        key = native.canonical(item)
        if key not in seen:
            first.append(copy.deepcopy(item))
            seen.add(key)


def retain_supplemental_frames(frames, supplements):
    """Retain explicit source rows only; never nearest-frame, PTS, pixel or camera borrowing."""
    identity_rows = {}
    for frame in frames:
        identity_rows.setdefault((frame["timeSeconds"], exposure_key(frame), layout_key(frame)), []).append(frame)
    for original in supplements:
        if original.get("decodedTimeSeconds") is None:
            raise ValueError("Historical supplemental source record has no actual decoded PTS")
        frame = source_frame(original)
        key = (frame["timeSeconds"], exposure_key(frame), layout_key(frame))
        matches = identity_rows.get(key, [])
        # Missing image identity is not an authority for exposure union.
        if exposure_key(frame) is not None and len(matches) == 1:
            existing = matches[0]
            known = {(p.get("viewId", "main"), p["anchorId"]): p for p in existing["landmarks"]}
            for point in frame["landmarks"]:
                prior = known.get((point.get("viewId", "main"), point["anchorId"]))
                if prior is not None and prior != point:
                    # Different declaration remains an original required loss,
                    # not a conveniently selected new measurement.
                    existing["unavailable"].append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                        "role": point.get("role"), "sourcePixels": point.get("pixel"), "required": True,
                        "reason": "Conflicting original declarations on the same exact exposure/layout; no measurement is selected"})
                elif prior is None:
                    existing["landmarks"].append(copy.deepcopy(point))
            union_declarations(existing["unavailable"], frame["unavailable"])
            if frame.get("sourceMachineRequirement") == "required":
                existing["sourceMachineRequirement"] = "required"
        else:
            frames.append(frame)
            identity_rows.setdefault(key, []).append(frame)
    frames.sort(key=lambda frame: (frame["timeSeconds"], frame["decodedTimeSeconds"], layout_key(frame) or ""))


def associate_source_body_facts(frames, association):
    """Retain source facts; one full raw-native body proof per exact authored path."""
    body_proofs = {}
    proof_digests = {}
    for frame in frames:
        contexts = [(frame, "main"), *[(view, view["id"]) for view in frame.get("views", [])]]
        for context, view_id in contexts:
            for field in ("nativeLineChecks", "sourceContourChecks", "sourceRodBodyMeasurements", "unresolvedSourceRodBodies"):
                for item in context.get(field, []):
                    path = item.get("partPath")
                    if not path:
                        continue
                    if path not in body_proofs:
                        body = association.associate_native_part(path)
                        serialized = native.canonical(body)
                        body_proofs[path] = {**body, "serializedProof": serialized}
                        proof_digests[path] = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
                    body = body_proofs[path]
                    proof = {"status": body["status"], "reason": body["reason"],
                             "proofRef": path, "proofSha256": proof_digests[path]}
                    item["nativeAssociation"] = proof
                    item["originalPartPath"] = path
                    # Historical residual/native-bias summaries are not current qualification.
                    for key in list(item):
                        if key.startswith("nativeCandidate"):
                            del item[key]
                    evidence = item.get("measurementEvidence")
                    if isinstance(evidence, dict):
                        old_bias = {key: evidence.pop(key) for key in ("axisPerspectiveBiasBoundPx", "axisPerspectiveEvidence") if key in evidence}
                        if old_bias:
                            item["historicalNativeEvidence"] = {"model": native.HISTORICAL_SOURCE, **old_bias}
                    world_line = item.get("partWorldLineMetres", item.get("worldLineMetres"))
                    if proof["status"] == "mapped" and world_line is not None:
                        if item.get("partLocalLineMetres") is not None or not isinstance(world_line, list) or not all(native.finite_vector(point, 3) for point in world_line):
                            proof["status"], proof["reason"] = "unavailable", "Original native line has ambiguous local/world coordinate authority"
                        else:
                            item["partLocalLineMetres"] = [native.localize_old_world(body["proof"]["historicalWorldMatrix"], point) for point in world_line]
                            item.pop("partWorldLineMetres", None)
                            item.pop("worldLineMetres", None)
                    if proof["status"] == "unavailable":
                        item.pop("partPath", None)
                        for key in ("partLocalLineMetres", "partWorldLineMetres", "worldLineMetres"):
                            item.pop(key, None)
                        frame["unavailable"].append({
                            "contourId": item.get("id", item.get("contourId")), "viewId": view_id,
                            "role": item.get("role"), "originalPartPath": path, "status": "unmeasured-native",
                            "required": True, "reason": proof["reason"]})
    return body_proofs


def retain_association_losses(frames, anchors):
    associations = {anchor["id"]: anchor["nativeAssociation"] for anchor in anchors}
    for frame in frames:
        losses = []
        for point in frame.get("landmarks", []):
            association = associations.get(point["anchorId"])
            if association is None or association["status"] == "unavailable":
                losses.append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "status": "unmeasured-native", "required": True,
                    "reason": association["reason"] if association else "Original source landmark has no uniquely identified native anchor"})
        # Source-only unidentified features/losses are requirements even when
        # they were not admitted as measured FIT/CHECK anchors.
        for point in frame.get("landmarks", []):
            if point.get("status") != "observed" or point.get("pixel") is None:
                losses.append({"anchorId": point["anchorId"], "viewId": point.get("viewId", "main"),
                    "role": point.get("role"), "sourcePixels": copy.deepcopy(point.get("pixel")),
                    "required": True, "reason": "Original required source feature is unresolved/unobserved; no measurement inferred"})
        for item in frame.get("sourceFeatureUnavailable", []):
            losses.append({**copy.deepcopy(item), "required": True} if isinstance(item, dict)
                          else {"reason": copy.deepcopy(item), "required": True})
        union_declarations(frame["unavailable"], losses)


def retain_declared_tracking_losses(frames, documents):
    """Top-level source-only loss events must reach the required frame ledger too."""
    by_exposure = {}
    for frame in frames:
        by_exposure.setdefault((frame["shotId"], frame["decodedTimeSeconds"]), []).append(frame)
    for document in documents:
        for loss in document.get("trackingLosses", []):
            matches = by_exposure.get((loss.get("shotId"), loss.get("decodedTimeSeconds")), [])
            if not matches:
                raise ValueError("Original tracking loss has no retained actual source exposure; cannot drop or invent its PTS")
            for frame in matches:
                declaration = {**copy.deepcopy(loss), "viewId": loss.get("viewId"),
                    "originalViewId": loss.get("viewId"), "role": loss.get("role"),
                    "sourcePixels": copy.deepcopy(loss.get("pixel")), "status": "source-unavailable", "required": True}
                union_declarations(frame["unavailable"], [declaration])

def adopt_video(video_id, association=None, historical_root=None):
    root = historical_root or common.HISTORICAL_CONTENT
    association = association or native.native_association()
    documents, lineage = [], []
    for suffix in ("observations", "track", "source-track"):
        path = root / f"{video_id}.{suffix}.json"
        if suffix == "track" and not path.exists():
            continue
        raw = path.read_bytes()
        document = json.loads(raw)
        if (document.get("source", {}).get("videoId") != video_id
                or any(document.get("model", {}).get(key) != value for key, value in native.HISTORICAL_SOURCE.items())):
            raise ValueError(f"Historical corpus does not target its original source/model: {path}")
        if documents and document["source"]["sha256"] != documents[0]["source"]["sha256"]:
            raise ValueError("Historical supplemental source differs from original footage")
        documents.append(document)
        lineage.append({"path": f"content/{path.name}", "sha256": native.hashlib.sha256(raw).hexdigest(),
                        "model": copy.deepcopy(document["model"]), "scope": "Immutable historical input; native/camera/GPU certificates not current qualification"})
    original = documents[0]
    anchor_catalog = {}
    conflicts = set()
    for document in documents:
        for anchor in document.get("anchors", []):
            prior = anchor_catalog.get(anchor["id"])
            if prior is None:
                anchor_catalog[anchor["id"]] = anchor
            elif any(prior.get(key) != anchor.get(key) for key in ("partPath", "partLocalMetres", "worldMetres")):
                conflicts.add(anchor["id"])
    rows = []
    for anchor_id, anchor in anchor_catalog.items():
        row = association.associate_native_anchor(anchor)
        if anchor_id in conflicts:
            reason = "Historical catalogs disagree on native feature coordinates/path; fresh primary mapping required"
            row = {"status": "unavailable", "reason": reason, "proof": row["proof"],
                   "anchor": {key: copy.deepcopy(anchor[key]) for key in ("id", "kind", "description") if key in anchor}}
            row["anchor"]["nativeAssociation"] = {"status": "unavailable", "reason": reason, "proof": row["proof"]}
        rows.append(row)
    frames = [source_frame(frame) for frame in original["frames"]]
    for document in documents[1:]:
        retain_supplemental_frames(frames, document["frames"])
    body_proofs = associate_source_body_facts(frames, association)
    anchors = [row["anchor"] for row in rows]
    retain_association_losses(frames, anchors)
    retain_declared_tracking_losses(frames, documents)
    compact_keys = {frame["timeSeconds"] for document in documents
                    if document.get("kind") == "compact-source-track" for frame in document["frames"]}
    compact_keys.update(original.get("compactChangeTimesSeconds", []))
    compact_keys.update(original.get("coverage", {}).get("changeTimesSeconds", []))
    coverage = {key: copy.deepcopy(value) for key, value in original.get("coverage", {}).items()
                if key in ("requiredEveryIntegerSecond", "requiredEveryChange", "requiredEveryNativeFrame", "changeTimesSeconds")}
    coverage.update({"status": "blocked", "requiredEveryIntegerSecond": True,
        "blockers": ["Current raw-native associations do not qualify original source-first-surface, complete inputs, camera fits, or actual GPU matching.",
                     "All six 50/20/10/5 source matching stages remain unmeasured.",
                     *[f'{row["anchor"].get("id")}: {row["reason"]}' for row in rows if row["status"] == "unavailable"]]})
    result = {"schemaVersion": original["schemaVersion"], "source": copy.deepcopy(original["source"]),
              "model": common.current_model_identity(), "anchors": anchors,
              "shots": [{key: copy.deepcopy(value) for key, value in shot.items() if key not in SHOT_NATIVE_FIELDS}
                        for shot in original["shots"]], "frames": frames, "coverage": coverage,
              "compactChangeTimesSeconds": sorted(compact_keys),
              "nativeBodyAssociations": body_proofs,
              "stages": {str(stage): {"status": "unmeasured"} for stage in (50, 20, 10, 5)},
              "sourceMeasurements": {"status": "partial", "blockers": coverage["blockers"]},
              "nativeAdoption": {"status": "associated-with-required-losses", "sourceAcceptance": False,
                    "GPUAcceptance": False, "mappedAnchorCount": sum(row["status"] == "mapped" for row in rows),
                    "unavailableAnchorCount": sum(row["status"] == "unavailable" for row in rows),
                    "historicalInputs": lineage,
                    "interpretation": "Exact original-source media facts plus fresh original-GLB native association. No old source certificate was relabelled."}}
    if original.get("nativeGeometryAssumptions"):
        result["nativeGeometryAssumptions"] = copy.deepcopy(original["nativeGeometryAssumptions"])
    if original.get("sourceCameraRigs"):
        result["sourceCameraRigs"] = [
            {key: copy.deepcopy(value) for key, value in rig.items()
             if key in ("kind", "id", "phaseCount", "phaseImages", "measurements", "independentLoopEvidence", "rejectedMeasurements")}
            for rig in original["sourceCameraRigs"]]
    if original.get("trackingLosses"):
        result["trackingLosses"] = copy.deepcopy(original["trackingLosses"])
    if original.get("operations"):
        result["operations"] = [{key: copy.deepcopy(value) for key, value in operation.items()
                                 if key in ("id", "timeRangeSeconds", "targets", "sourceFeatureMeasurements")}
                                for operation in original["operations"]]
    return result


def _publish_six_records(prepared, suffix, current_root=None):
    """All-or-nothing current directory transaction; preserve other current packets."""
    target = current_root or common.CURRENT_CONTENT
    if set(prepared) != set(common.VIDEO_IDS):
        raise ValueError("Only the complete six-video current corpus transaction may publish")
    target.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".v39-{suffix}-", dir=target.parent))
    backup = staging / "previous"
    staged = staging / "current"
    had_target = target.exists()
    published = False
    try:
        if had_target:
            shutil.copytree(target, staged)
        else:
            staged.mkdir()
        for video_id, data in prepared.items():
            if data.get("model") != common.current_model_identity() or data.get("source", {}).get("videoId") != video_id:
                raise ValueError("Prepared current record model/video identity mismatch")
            (staged / f"{video_id}.{suffix}.json").write_text(json.dumps(data, separators=(",", ":"), allow_nan=False) + "\n")
        if had_target:
            os.replace(target, backup)
        try:
            os.replace(staged, target)
            published = True
        except BaseException:
            if had_target:
                os.replace(backup, target)
            raise
    finally:
        if published or not backup.exists():
            shutil.rmtree(staging)


def publish_observations(prepared, current_root=None):
    return _publish_six_records(prepared, "observations", current_root)


def publish_tracks(prepared, current_root=None):
    for track in prepared.values():
        if (track.get("kind") != "compact-source-track"
                or track.get("stages") != {str(stage): {"status": "unmeasured"} for stage in (50, 20, 10, 5)}):
            raise ValueError("Current generation must publish compact tracks with all four stages unmeasured")
        common.prepare_track(track)
    return _publish_six_records(prepared, "source-track", current_root)


def main():
    association = native.native_association()
    prepared = {video_id: adopt_video(video_id, association) for video_id in common.VIDEO_IDS}
    publish_observations(prepared)
    print(json.dumps({"contentRoot": "web/content/v39", "videos": [
        {"videoId": video_id, "frames": len(data["frames"]),
         "mappedAnchors": data["nativeAdoption"]["mappedAnchorCount"],
         "unavailableAnchors": data["nativeAdoption"]["unavailableAnchorCount"],
         "sourceAcceptance": False, "GPUAcceptance": False} for video_id, data in prepared.items()]}))


if __name__ == "__main__":
    main()
