"""Copy CAD build artefacts into the book's figure tree.

`cad/out/` is a build artefact (gitignored, regenerated by `doit`), so chapters
must not reference it directly — a path into `cad/out` breaks for anyone who
hasn't run the SolidWorks build, and it makes the book silently depend on
whatever happened to be on disk.

This script copies the renders and drawing sheets into
`book/figures/generated/` (also gitignored) and writes `manifest.json`
recording what was copied, from where, its size and its SHA-256. A chapter
references `figures/generated/renders/<stem>.png`; the manifest answers "which
build produced the figure in this PDF?".

    uv run python book/scripts/collect_figures.py            # copy what's there
    uv run python book/scripts/collect_figures.py --check    # report only

Run `uv run python -m doit build` first if `cad/out/` is empty or stale.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CAD_OUT = REPO / "cad" / "out"
FIGURES = REPO / "book" / "figures" / "generated"

# (source dir under cad/out, glob, destination under figures/generated)
SOURCES = [
    (CAD_OUT / "png", "*.png", "renders"),
    (CAD_OUT / "pdf", "*.pdf", "drawings"),
]

# Tracked, hand-made figures live beside the generated ones and are never
# touched by this script.
HAND = REPO / "book" / "figures" / "hand"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report what would be copied, copy nothing")
    args = ap.parse_args()

    if not CAD_OUT.exists():
        print(f"xx cad/out not found at {CAD_OUT}\n"
              f"   run `uv run python -m doit build` on the SolidWorks seat first,\n"
              f"   or `gh release download` a release bundle.", file=sys.stderr)
        return 1

    entries: list[dict] = []
    copied = missing = 0

    for src_dir, pattern, dest_name in SOURCES:
        dest_dir = FIGURES / dest_name
        if not src_dir.exists():
            print(f"!! {src_dir.relative_to(REPO)} absent — skipping {dest_name}")
            missing += 1
            continue
        if not args.check:
            dest_dir.mkdir(parents=True, exist_ok=True)
        for src in sorted(src_dir.glob(pattern)):
            dest = dest_dir / src.name
            if not args.check:
                shutil.copy2(src, dest)
            entries.append({
                "figure": f"figures/generated/{dest_name}/{src.name}",
                "source": str(src.relative_to(REPO)).replace("\\", "/"),
                "bytes": src.stat().st_size,
                "sha256": sha256(src),
            })
            copied += 1

    if args.check:
        print(f"-- {copied} figure(s) available, {missing} source dir(s) missing")
        return 0

    FIGURES.mkdir(parents=True, exist_ok=True)
    HAND.mkdir(parents=True, exist_ok=True)
    manifest = {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "count": len(entries),
        "figures": entries,
    }
    (FIGURES / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"   OK  {copied} figure(s) -> {FIGURES.relative_to(REPO)}")
    if missing:
        print(f"!! {missing} source dir(s) missing — the book will render with gaps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
