gooseneck-set-screw:
  title: Steel Square-Head Cup-Point Set Screw
  number: MHA-118
  stock_name: Steel Square-Head Cup-Point Set Screw
  supplier: McMaster-Carr
  supplier_skus: [91410A538]
  material: Plain Carbon Steel
  material_specification: Steel, McMaster-Carr 91410A538
  finish: as supplied
  quantity: 1
  tolerance_class: machined_block
  process: purchased
