spring-hook:
  number: MHA-090
  material: Plain Carbon Steel
  material_specification: AISI 1018 steel wire, 1.4 dia
  finish: black oxide
  quantity: 20
  tolerance_class: machined_block
  process: "formed wire"
